import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';

type Language = 'en' | 'ru' | 'fr' | 'de' | 'es' | 'zh' | 'ar' | 'pt' | 'ja' | 'ko' | 'hi' | 'it' | 'tr' | 'vi' | 'th' | 'hu' | 'cs' | 'el' | 'pl' | 'ro' | 'da' | 'et' | 'fi' | 'nl' | 'no' | 'sk' | 'sl' | 'sv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'home': 'Home',
    'about': 'About',
    'investments': 'Investments',
    'security': 'Security',
    'dashboard': 'Dashboard',
    
    // Header
    'invest': 'Invest',
    'signOut': 'Sign Out',
    'admin': 'Admin',
    
    // Stats
    'totalInvested': 'Total Invested',
    'totalProfit': 'Total Profit',
    'pending': 'Pending',
    'active': 'Active',
    'marketCap': 'Market Cap',
    'stockPrice': 'Stock Price',
    'globalDeliveries': 'Global Deliveries',
    'superchargers': 'Superchargers',
    
    // Investment Form
    'makeNewInvestment': 'Make New Investment',
    'investmentAmount': 'Investment Amount (USD)',
    'enterAmount': 'Enter amount (min $100)',
    'submitInvestment': 'Submit Investment Request',
    'processingText': 'Processing...',
    'contactViaWhatsapp': 'Our team will contact you via WhatsApp to complete the investment',
    'minInvestment': 'Minimum investment is $100',
    'investmentSubmitted': 'Investment request submitted! Our team will contact you shortly.',
    'loadingPayment': 'Loading payment details...',
    
    // Payment Details
    'paymentDetails': 'Payment Details',
    'investmentDetails': 'Investment Details',
    'bankName': 'Bank Name',
    'accountHolder': 'Account Holder',
    'cardNumber': 'Card Number',
    'copied': 'Copied!',
    'walletCopied': 'Wallet address copied!',
    'sendReceiptVia': 'Send payment receipt via WhatsApp after transfer',
    'dashboardSubtitle': 'Manage your investments and track your profits',
    
    // Investment History
    'investmentHistory': 'Investment History',
    'noInvestments': 'No investments yet. Start your journey today!',
    'profit': 'profit',
    
    // Chart
    'performanceChart': 'Investment Performance',
    'teslaStock': 'Tesla Stock Performance',
    
    // Notifications
    'profitNotification': 'New profit received!',
    'profitMessage': 'Your investment earned',
    
    // Currency
    'usdToRub': 'Converted to RUB',
    'exchangeRate': 'Exchange rate: 1 USD = ',
    
    // Auth
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'fullName': 'Full Name',
    'welcomeBack': 'Welcome Back',
    'createAccount': 'Create Account',
    'forgotPassword': 'Forgot Password?',
    'resetPassword': 'Reset Password',
    'enterPhone': 'Enter your registered phone number',
    'phoneNumber': 'Phone Number',
    'newPassword': 'New Password',
    'confirmPassword': 'Confirm Password',
    'passwordChanged': 'Password changed successfully!',
    'invalidPhone': 'Invalid phone number',
    'backToLogin': 'Back to Login',
    'signInSubtitle': 'Sign in to access your account',
    'createAccountSubtitle': 'Create an account to get started',
    'continueWithGoogle': 'Continue with Google',
    'connecting': 'Connecting...',
    'or': 'or',
    'enterFullName': 'Enter your full name',
    'enterEmail': 'Enter your email address',
    'enterPassword': 'Enter your password',
    'noAccount': "Don't have an account? ",
    'alreadyHaveAccount': 'Already have an account? ',
    'termsAgreement': 'By continuing, you agree to our Terms of Service and Privacy Policy',
    
    // Hero
    'heroTitle': 'Invest in the',
    'heroTitleHighlight': 'Future of Electric Mobility',
    'heroSubtitle': 'Trade and track Tesla stocks in real-time. Join thousands of investors capitalizing on Tesla\'s revolutionary growth.',
    'getStarted': 'Get Started',
    'learnMore': 'Learn More',
    
    // Language
    'language': 'Language',
    'english': 'English',
    'russian': 'Русский',
    'french': 'Français',
    'german': 'Deutsch',
    'spanish': 'Español',
    'chinese': '中文',
    'arabic': 'العربية',
    'portuguese': 'Português',
    'japanese': '日本語',
    'korean': '한국어',
    'hindi': 'हिंदी',
    'italian': 'Italiano',
    'turkish': 'Türkçe',
    'vietnamese': 'Tiếng Việt',
    'thai': 'ไทย',
    'hungarian': 'Magyar',
    'czech': 'Čeština',
    'greek': 'Ελληνικά',
    'polish': 'Polski',
    'romanian': 'Română',
    'danish': 'Dansk',
    'estonian': 'Eesti',
    'finnish': 'Suomi',
    'dutch': 'Nederlands',
    'norwegian': 'Norsk',
    'slovak': 'Slovenčina',
    'slovenian': 'Slovenščina',
    'swedish': 'Svenska',
    
    // Footer
    'footerDescription': 'Tesla Stock is a premier investment platform specializing in electric vehicle and sustainable energy stocks. We provide secure, transparent, and profitable investment opportunities.',
    'company': 'Company',
    'aboutUs': 'About Us',
    'ourTeam': 'Our Team',
    'careers': 'Careers',
    'contact': 'Contact',
    'legal': 'Legal',
    'termsOfService': 'Terms of Service',
    'privacyPolicy': 'Privacy Policy',
    'riskDisclosure': 'Risk Disclosure',
    'cookiePolicy': 'Cookie Policy',
    'regulatory': 'Regulatory',
    'license': 'License',
    'compliance': 'Compliance',
    'amlPolicy': 'AML Policy',
    'investorProtection': 'Investor Protection',
    'regulatedEntity': 'Regulated Investment Platform',
    'licenseNumber': 'License Number',
    'allRightsReserved': 'All rights reserved.',
    'registrationInfo': 'Registered in California, USA. Registration No. 2024-INV-001234',
    
    // Testimonials
    'testimonialTitle': 'What Our Investors Say',
    'testimonialSubtitle': 'Join thousands of satisfied investors worldwide',
    'investor': 'Investor',
    'testimonial1': 'Tesla Stock has completely transformed my investment portfolio. The returns have been exceptional and the platform is incredibly easy to use.',
    'testimonial2': 'I was skeptical at first, but after seeing consistent profits for 6 months, I am now a believer. Highly recommend to anyone looking to invest in the future.',
    'testimonial3': 'The transparency and professionalism of Tesla Stock is unmatched. I feel secure knowing my investments are in good hands.',
    'testimonial4': 'Started with a small investment and have grown it significantly. The real-time tracking and profit notifications are fantastic.',
    'testimonial5': 'Best investment decision I have ever made. The team is responsive and the platform delivers on its promises.',
    'testimonial6': 'The platform has exceeded my expectations. Real-time tracking and expert market insights have helped me make smarter investment decisions.',
    'ceoQuote': 'Invest in the future where innovation meets sustainable returns. Tesla stock represents the convergence of technology, clean energy, and unprecedented market growth.',
    
    // Stock Growth
    'marketLeader': 'Market Leader',
    'stockGrowthTitle': 'Tesla Stock:',
    'exponentialGrowth': 'Exponential Growth',
    'stockGrowthDesc': 'Tesla has consistently outperformed the market, delivering exceptional returns to early investors. Join the movement today.',
    'yearToDate': 'Year to Date',
    'fiveYear': '5 Year Return',
    'sinceIPO': 'Since IPO',
    
    // Admin
    'adminPasscode': 'Enter Admin Passcode',
    'accessDenied': 'Access Denied',
    'enterPasscode': 'Enter passcode to access admin panel',
    'defaultLanguage': 'Default Language',
    'setDefaultLanguage': 'Set Default Language',
    'adminPanel': 'Admin Panel',
    'paymentSettings': 'Payment Settings',
    'withdrawalSettings': 'Withdrawal Settings',
    'supportSettings': 'Customer Support Settings',
    'defaultHoldMessage': 'Default Hold Message',
    'supportType': 'Support Type',
    'supportPhone': 'Support Phone/Username',
    'savePaymentSettings': 'Save Payment Settings',
    'saveWithdrawalSettings': 'Save Withdrawal Settings',
    'saveSupportSettings': 'Save Support Settings',
    'noInvestmentsYet': 'No investments yet',
    'noWithdrawalsYet': 'No withdrawals yet',
    'setProfit': 'Set Profit',
    'sendProfitEmail': 'Send Profit Email',
    'approve': 'Approve',
    'cancel': 'Cancel',
    'complete': 'Complete',
    'processing': 'Processing',
    'hold': 'Hold',
    'editMessage': 'Edit Message',
    'setPending': 'Set Pending',
    'putOnHold': 'Put on Hold',
    'setProcessing': 'Set Processing',
    'holdBillingMessage': 'Hold/Billing Fee Message',
    'autoGenerateFee': 'Auto Generate Fee',
    'quickTemplates': 'Quick Templates',
    'saveAndNotify': 'Save & Notify',
    'securityLogs': 'Security Logs',
    'loginAttempts': 'Login Attempts',
    'refreshLogs': 'Refresh',
    'success': 'Success',
    'failed': 'Failed',
    'userAgent': 'User Agent',
    'securityInfo': 'Security Information',
    'emailMonitoring': 'Email Monitoring',
    'user': 'User',
    'date': 'Date',
    'country': 'Country',
    'paymentDetailsLabel': 'Payment Details',
    'holdMessage': 'Hold Message',
    
    // Referral
    'referralCode': 'Referral Code',
    'enterReferralCode': 'Enter Referral Code',
    'optional': 'optional',
    'invalidReferralCode': 'Invalid referral code. Please check and try again.',
    'referralSettings': 'Referral Settings',
    'referralEmail': 'Notification Email',
    'saveReferralSettings': 'Save Referral Settings',
    
    // Portfolio
    'portfolioBalance': 'Portfolio Balance',
    'noBalanceYet': 'No Balance Yet',
    'investment': 'Investment',
    // Investment Steps
    'investmentSteps': 'Steps to Complete Investment:',
    'step1': 'Make payment to the account details above',
    'step2': 'Send payment receipt via WhatsApp',
    'step3': 'Click "Submit Investment Request"',
    
    // Vision Section
    'visionTitle': 'The Investment Opportunity',
    'visionSubtitle': 'Why smart investors are choosing Tesla for exponential portfolio growth',
    'sustainableEnergy': 'Sustainable Energy',
    'sustainableEnergyDesc': 'Accelerating the world\'s transition to renewable energy',
    'autonomousFuture': 'Autonomous Future',
    'autonomousFutureDesc': 'Full self-driving technology changing transportation',
    'globalScale': 'Global Scale',
    'globalScaleDesc': 'Manufacturing excellence with Gigafactories worldwide',
    
    // Investment Reasons
    'whyInvest': 'Why Invest in Tesla?',
    'sixReasons': 'Six compelling reasons to consider Tesla for your portfolio',
    'reason1': 'Market leader in EV industry with 20%+ market share',
    'reason2': 'Vertically integrated manufacturing reducing costs',
    'reason3': 'Growing energy storage and solar business',
    'reason4': 'Expanding AI and autonomous driving capabilities',
    'reason5': 'Strong brand loyalty and customer satisfaction',
    'reason6': 'Global expansion with new Gigafactories',
    'getStartedToday': 'Get Started Today',
    'downloadProspectus': 'Download Prospectus',
    
    // Features Section
    'whyChooseUs': 'Why Choose Us',
    'featuresTitle': 'Everything You Need to Invest',
    'featuresSubtitle': 'A complete platform designed for both beginners and experienced investors.',
    'featureSecurity': 'Bank-Level Security',
    'featureSecurityDesc': 'Your investments are protected with 256-bit encryption and multi-factor authentication.',
    'featureInstant': 'Instant Transactions',
    'featureInstantDesc': 'Execute trades in milliseconds with our high-performance trading infrastructure.',
    'featureMobile': 'Mobile Optimized',
    'featureMobileDesc': 'Full-featured trading experience on any device, anywhere in the world.',
    'featureAnalytics': 'Real-Time Analytics',
    'featureAnalyticsDesc': 'Track your portfolio performance with live charts and detailed insights.',
    'featureWithdrawals': 'Fast Withdrawals',
    'featureWithdrawalsDesc': 'Access your funds within 24 hours via bank transfer or cryptocurrency.',
    'featureSupport': '24/7 Support',
    'featureSupportDesc': 'Dedicated support team available around the clock to assist you.',
    
    // How It Works
    'gettingStarted': 'Getting Started',
    'howItWorks': 'How It Works',
    'howItWorksSubtitle': 'Start your investment journey in four simple steps.',
    'step': 'Step',
    'howStep1Title': 'Create Your Account',
    'howStep1Desc': 'Sign up in under 2 minutes with your email. Verification is quick and secure.',
    'howStep2Title': 'Fund Your Wallet',
    'howStep2Desc': 'Deposit funds via bank transfer, credit card, or cryptocurrency.',
    'howStep3Title': 'Invest in Tesla',
    'howStep3Desc': 'Purchase Tesla shares starting from just $100 with instant confirmation.',
    'howStep4Title': 'Grow & Withdraw',
    'howStep4Desc': 'Watch your investment grow and withdraw profits anytime you want.',
    
    // Innovations
    'innovationsTitle': 'Leading Innovation',
    'innovationsSubtitle': 'Tesla\'s technological breakthroughs are reshaping entire industries',
    'innovationBattery': 'Battery Technology',
    'innovationBatteryDesc': 'Revolutionary 4680 cells delivering longer range, faster charging, and lower costs',
    'innovationBatteryStat': '500+ miles range',
    'innovationAI': 'AI & Full Self-Driving',
    'innovationAIDesc': 'Neural networks processing real-world data to achieve autonomous driving',
    'innovationAIStat': '150M+ miles driven',
    'innovationSupercharger': 'Global Supercharger Network',
    'innovationSuperchargerDesc': 'The world\'s fastest EV charging network with strategic global coverage',
    'innovationSuperchargerStat': '50K+ stations',
    'innovationSpaceX': 'SpaceX Synergy',
    'innovationSpaceXDesc': 'Cross-innovation between Tesla and SpaceX driving breakthrough technologies',
    'innovationSpaceXStat': 'Multi-planetary vision',
    
    // FAQ
    'support': 'Support',
    'faqTitle': 'Frequently Asked',
    'faqTitleHighlight': 'Questions',
    'faqSubtitle': 'Got questions? We\'ve got answers. Find everything you need to know about investing with us.',
    'faqQuestion1': 'Is this the real Tesla stock?',
    'faqAnswer1': 'Yes, we provide access to genuine Tesla (TSLA) stock investments through regulated and licensed financial partners. Your investments are backed by actual Tesla shares traded on major stock exchanges. We ensure full transparency and compliance with financial regulations.',
    'faqQuestion2': 'How secure are my investments?',
    'faqAnswer2': 'Your investments are protected by bank-level SSL encryption and stored in secure, regulated accounts. We use multi-factor authentication, advanced fraud detection, and cold storage for assets. Our platform undergoes regular security audits by independent firms to ensure the highest level of protection.',
    'faqQuestion3': 'How do I withdraw my profits?',
    'faqAnswer3': 'Withdrawing is simple! Go to your Dashboard, click on "Withdraw Funds," enter the amount you wish to withdraw, select your preferred payment method (cryptocurrency or bank transfer), and submit your request. Withdrawals are typically processed within 24-48 hours for crypto and 3-5 business days for bank transfers.',
    'faqQuestion4': 'What is the minimum investment amount?',
    'faqAnswer4': 'You can start investing with as little as $100. This low entry barrier makes Tesla stock accessible to everyone, whether you\'re a beginner or an experienced investor looking to diversify your portfolio.',
    
    // Withdrawal Form
    'withdraw': 'Withdraw',
    'withdrawProfit': 'Withdraw Profit',
    'withdrawalAmount': 'Withdrawal Amount',
    'availableForWithdrawal': 'Available for withdrawal',
    'withdrawAll': 'Withdraw all',
    'selectCountry': 'Select Your Country',
    'chooseCountry': 'Choose your country',
    'searchCountries': 'Search countries...',
    'selectMethod': 'Select Withdrawal Method',
    'bankCard': 'Bank Card',
    'bankCardDesc': 'Withdraw to your bank card',
    'mobilePayment': 'Mobile Payment',
    'mobilePaymentDesc': 'SBP or phone number transfer',
    'cryptoPayment': 'Cryptocurrency',
    'cryptoPaymentDesc': 'Withdraw to crypto wallet',
    'enterPaymentDetails': 'Enter Payment Details',
    'enterCardNumber': 'Enter your card number',
    'enterPhoneNumber': 'Enter your phone number',
    'enterCryptoAddress': 'Enter wallet address (USDT TRC-20)',
    'amount': 'Amount',
    'method': 'Method',
    'reviewWithdrawal': 'Review & Submit',
    'submitWithdrawal': 'Submit Withdrawal Request',
    'submittingWithdrawal': 'Submitting...',
    'next': 'Next',
    'back': 'Back',
    'sberbankNotice': 'Sberbank transfers may take additional time. Please allow up to 24 hours for processing.',
    'withdrawalOnHold': 'Withdrawal On Hold',
    'withdrawalPending': 'Withdrawal Pending',
    'withdrawalCompleted': 'Withdrawal Completed',
    'contactSupport': 'Contact Support',
    'noProfitYet': 'No Profit Yet',
    'clickToWithdraw': 'Click to Withdraw',
    
    // Withdrawal availability
    'completedInvestments': 'Completed Investments',
    'investmentPlusProfit': 'Investment + Profit available',
    'activeProfit': 'Active Trading Profit',
    'profitOnlyWithdrawal': 'Only profit withdrawable while trading',
    'noWithdrawalAvailable': 'Investment still in progress. Withdraw available once trading completes.',
    'viewTransactionHistory': 'View Full Transaction History',
    'pendingWithdrawalExists': 'You already have a pending withdrawal request. Please wait for it to be processed.',
    'withdrawn': 'Withdrawn',
    
    // Crypto Payment
    'cryptoWarning': 'Please make sure that only USDT deposit is made via this address. Otherwise, your investment will not be activated.',
    'howToPayCrypto': 'How to Make USDT Payment:',
    'cryptoStep1': 'Copy the USDT wallet address above',
    'cryptoStep2': 'Open your crypto wallet and send the exact USDT amount using TRON (TRC20) network',
    'cryptoStep3': 'Take a screenshot of the transaction and send confirmation via WhatsApp',
    'cryptoStep4': 'Press "Submit Investment Request" button below',
    'searchCountry': 'Search Country',
    'noCountriesFound': 'No countries found',
    'countryRequired': 'Please select your country to see payment options',
    'network': 'Network',
    'walletAddress': 'USDT Wallet Address',
    'amountToSend': 'Amount to Send',
    'important': 'Important',
  },
  ru: {
    // Navigation
    'home': 'Главная',
    'about': 'О нас',
    'investments': 'Инвестиции',
    'security': 'Безопасность',
    'dashboard': 'Панель',
    
    // Header
    'invest': 'Инвестиции',
    'signOut': 'Выйти',
    'admin': 'Админ',
    
    // Stats
    'totalInvested': 'Всего инвестировано',
    'totalProfit': 'Общая прибыль',
    'pending': 'В ожидании',
    'active': 'Активные',
    'marketCap': 'Капитализация',
    'stockPrice': 'Цена акций',
    'globalDeliveries': 'Поставки',
    'superchargers': 'Суперчарджеры',
    
    // Investment Form
    'makeNewInvestment': 'Новая инвестиция',
    'investmentAmount': 'Сумма инвестиции (USD)',
    'enterAmount': 'Введите сумму (мин. $100)',
    'submitInvestment': 'Отправить заявку на инвестицию',
    'processingText': 'Обработка...',
    'contactViaWhatsapp': 'Наша команда свяжется с вами через WhatsApp для завершения инвестиции',
    'minInvestment': 'Минимальная инвестиция $100',
    'investmentSubmitted': 'Заявка на инвестицию отправлена! Наша команда скоро свяжется с вами.',
    'loadingPayment': 'Загрузка платежных реквизитов...',
    
    // Payment Details
    'paymentDetails': 'Платежные реквизиты',
    'investmentDetails': 'Детали инвестиции',
    'bankName': 'Наименование банка',
    'accountHolder': 'Владелец счета',
    'cardNumber': 'Номер карты',
    'copied': 'Скопировано!',
    'walletCopied': 'Адрес кошелька скопирован!',
    'dashboardSubtitle': 'Управляйте своими инвестициями и отслеживайте прибыль',
    'sendReceiptVia': 'Отправьте квитанцию об оплате через WhatsApp после перевода',
    
    // Investment History
    'investmentHistory': 'История инвестиций',
    'noInvestments': 'Пока нет инвестиций. Начните свой путь сегодня!',
    'profit': 'прибыль',
    
    // Chart
    'performanceChart': 'Показатели инвестиций',
    'teslaStock': 'Динамика акций Tesla',
    
    // Notifications
    'profitNotification': 'Получена новая прибыль!',
    'profitMessage': 'Ваша инвестиция заработала',
    
    // Currency
    'usdToRub': 'Конвертировано в RUB',
    'exchangeRate': 'Курс: 1 USD = ',
    
    // Auth
    'signIn': 'Войти',
    'signUp': 'Регистрация',
    'email': 'Электронная почта',
    'password': 'Пароль',
    'fullName': 'Полное имя',
    'welcomeBack': 'С возвращением',
    'createAccount': 'Создать аккаунт',
    'forgotPassword': 'Забыли пароль?',
    'resetPassword': 'Сбросить пароль',
    'enterPhone': 'Введите ваш зарегистрированный номер телефона',
    'phoneNumber': 'Номер телефона',
    'newPassword': 'Новый пароль',
    'confirmPassword': 'Подтвердите пароль',
    'passwordChanged': 'Пароль успешно изменен!',
    'invalidPhone': 'Неверный номер телефона',
    'backToLogin': 'Назад к входу',
    'signInSubtitle': 'Войдите, чтобы получить доступ к вашему аккаунту',
    'createAccountSubtitle': 'Создайте аккаунт, чтобы начать',
    'continueWithGoogle': 'Продолжить с Google',
    'connecting': 'Подключение...',
    'or': 'или',
    'enterFullName': 'Введите ваше полное имя',
    'enterEmail': 'Введите ваш email',
    'enterPassword': 'Введите ваш пароль',
    'noAccount': 'Нет аккаунта? ',
    'alreadyHaveAccount': 'Уже есть аккаунт? ',
    'termsAgreement': 'Продолжая, вы соглашаетесь с Условиями использования и Политикой конфиденциальности',
    
    // Hero
    'heroTitle': 'Инвестируйте в',
    'heroTitleHighlight': 'Будущее электромобильности',
    'heroSubtitle': 'Торгуйте и отслеживайте акции Tesla в реальном времени. Присоединяйтесь к тысячам инвесторов, извлекающих выгоду из революционного роста Tesla.',
    'getStarted': 'Начать',
    'learnMore': 'Узнать больше',
    
    // Language
    'language': 'Язык',
    'english': 'English',
    'russian': 'Русский',
    'french': 'Français',
    'german': 'Deutsch',
    'spanish': 'Español',
    'chinese': '中文',
    'arabic': 'العربية',
    'portuguese': 'Português',
    'japanese': '日本語',
    'korean': '한국어',
    'hindi': 'हिंदी',
    'italian': 'Italiano',
    'turkish': 'Türkçe',
    'vietnamese': 'Tiếng Việt',
    'thai': 'ไทย',
    'hungarian': 'Magyar',
    'czech': 'Čeština',
    'greek': 'Ελληνικά',
    'polish': 'Polski',
    'romanian': 'Română',
    'danish': 'Dansk',
    'estonian': 'Eesti',
    'finnish': 'Suomi',
    'dutch': 'Nederlands',
    'norwegian': 'Norsk',
    'slovak': 'Slovenčina',
    'slovenian': 'Slovenščina',
    'swedish': 'Svenska',
    
    // Footer
    'footerDescription': 'Tesla Stock — ведущая инвестиционная платформа, специализирующаяся на акциях электромобилей и устойчивой энергетики.',
    'company': 'Компания',
    'aboutUs': 'О нас',
    'ourTeam': 'Наша команда',
    'careers': 'Карьера',
    'contact': 'Контакты',
    'legal': 'Юридическая информация',
    'termsOfService': 'Условия использования',
    'privacyPolicy': 'Политика конфиденциальности',
    'riskDisclosure': 'Раскрытие рисков',
    'cookiePolicy': 'Политика cookie',
    'regulatory': 'Регулирование',
    'license': 'Лицензия',
    'compliance': 'Соответствие',
    'amlPolicy': 'Политика ПОД/ФТ',
    'investorProtection': 'Защита инвесторов',
    'regulatedEntity': 'Регулируемая инвестиционная платформа',
    'licenseNumber': 'Номер лицензии',
    'allRightsReserved': 'Все права защищены.',
    'registrationInfo': 'Зарегистрировано в Калифорнии, США.',
    
    // All other keys
    'testimonialTitle': 'Отзывы наших инвесторов',
    'testimonialSubtitle': 'Присоединяйтесь к тысячам довольных инвесторов',
    'investor': 'Инвестор',
    'marketLeader': 'Лидер рынка',
    'stockGrowthTitle': 'Акции Tesla:',
    'exponentialGrowth': 'Экспоненциальный рост',
    'stockGrowthDesc': 'Tesla стабильно превосходит рынок.',
    'yearToDate': 'С начала года',
    'fiveYear': 'За 5 лет',
    'sinceIPO': 'С IPO',
    'adminPasscode': 'Введите пароль администратора',
    'accessDenied': 'Доступ запрещен',
    'enterPasscode': 'Введите пароль для доступа к панели администратора',
    'defaultLanguage': 'Язык по умолчанию',
    'setDefaultLanguage': 'Установить язык по умолчанию',
    'adminPanel': 'Панель администратора',
    'paymentSettings': 'Настройки платежей',
    'withdrawalSettings': 'Настройки вывода',
    'supportSettings': 'Настройки поддержки',
    'defaultHoldMessage': 'Сообщение удержания по умолчанию',
    'supportType': 'Тип поддержки',
    'supportPhone': 'Телефон/имя поддержки',
    'savePaymentSettings': 'Сохранить настройки платежей',
    'saveWithdrawalSettings': 'Сохранить настройки вывода',
    'saveSupportSettings': 'Сохранить настройки поддержки',
    'noInvestmentsYet': 'Пока нет инвестиций',
    'noWithdrawalsYet': 'Пока нет выводов',
    'setProfit': 'Установить прибыль',
    'sendProfitEmail': 'Отправить email о прибыли',
    'approve': 'Одобрить',
    'cancel': 'Отмена',
    'complete': 'Завершить',
    'processing': 'Обработка',
    'hold': 'Удержание',
    'editMessage': 'Редактировать сообщение',
    'setPending': 'Установить в ожидание',
    'putOnHold': 'Поставить на удержание',
    'setProcessing': 'Установить обработку',
    'referralCode': 'Реферальный код',
    'enterReferralCode': 'Введите реферальный код',
    'optional': 'необязательно',
    'invalidReferralCode': 'Неверный реферальный код.',
    'portfolioBalance': 'Баланс портфеля',
    'noBalanceYet': 'Нет баланса',
    'investment': 'Инвестиция',
    'investmentSteps': 'Шаги для завершения инвестиции:',
    'step1': 'Сделайте платеж по указанным реквизитам',
    'step2': 'Отправьте квитанцию об оплате через WhatsApp',
    'step3': 'Нажмите "Отправить заявку на инвестицию"',
    'whyChooseUs': 'Почему мы',
    'featuresTitle': 'Всё для инвестиций',
    'featuresSubtitle': 'Полноценная платформа для начинающих и опытных инвесторов.',
    'featureSecurity': 'Банковская безопасность',
    'featureSecurityDesc': 'Ваши инвестиции защищены 256-битным шифрованием.',
    'featureInstant': 'Мгновенные транзакции',
    'featureInstantDesc': 'Выполняйте сделки за миллисекунды.',
    'featureMobile': 'Мобильная оптимизация',
    'featureMobileDesc': 'Полнофункциональная торговля на любом устройстве.',
    'featureAnalytics': 'Аналитика в реальном времени',
    'featureAnalyticsDesc': 'Отслеживайте показатели портфеля с помощью графиков.',
    'featureWithdrawals': 'Быстрые выводы',
    'featureWithdrawalsDesc': 'Получите доступ к средствам в течение 24 часов.',
    'featureSupport': 'Поддержка 24/7',
    'featureSupportDesc': 'Специализированная команда поддержки.',
    'gettingStarted': 'Начало работы',
    'howItWorks': 'Как это работает',
    'howItWorksSubtitle': 'Начните инвестировать за четыре простых шага.',
    'step': 'Шаг',
    'howStep1Title': 'Создайте аккаунт',
    'howStep1Desc': 'Зарегистрируйтесь за 2 минуты.',
    'howStep2Title': 'Пополните кошелек',
    'howStep2Desc': 'Внесите средства банковским переводом или криптовалютой.',
    'howStep3Title': 'Инвестируйте в Tesla',
    'howStep3Desc': 'Покупайте акции Tesla от $100.',
    'howStep4Title': 'Получайте прибыль',
    'howStep4Desc': 'Наблюдайте за ростом инвестиций.',
    'innovationsTitle': 'Лидерство в инновациях',
    'innovationsSubtitle': 'Технологические прорывы Tesla меняют отрасли',
    'innovationBattery': 'Технология батарей',
    'innovationBatteryDesc': 'Революционные ячейки 4680',
    'innovationBatteryStat': '500+ миль запас хода',
    'innovationAI': 'ИИ и автопилот',
    'innovationAIDesc': 'Нейронные сети для автономного вождения',
    'innovationAIStat': '150M+ миль',
    'innovationSupercharger': 'Сеть Supercharger',
    'innovationSuperchargerDesc': 'Самая быстрая сеть зарядки',
    'innovationSuperchargerStat': '50K+ станций',
    'innovationSpaceX': 'Синергия SpaceX',
    'innovationSpaceXDesc': 'Кросс-инновации Tesla и SpaceX',
    'innovationSpaceXStat': 'Межпланетное видение',
    'support': 'Поддержка',
    'faqTitle': 'Часто задаваемые',
    'faqTitleHighlight': 'вопросы',
    'faqSubtitle': 'Есть вопросы? У нас есть ответы.',
    'faqQuestion1': 'Это настоящие акции Tesla?',
    'faqAnswer1': 'Да, мы предоставляем доступ к реальным акциям Tesla.',
    'faqQuestion2': 'Насколько безопасны мои инвестиции?',
    'faqAnswer2': 'Ваши инвестиции защищены банковским SSL-шифрованием.',
    'faqQuestion3': 'Как вывести прибыль?',
    'faqAnswer3': 'Перейдите в панель и нажмите "Вывод средств".',
    'faqQuestion4': 'Какова минимальная сумма инвестиции?',
    'faqAnswer4': 'Вы можете начать инвестировать от $100.',
    'withdraw': 'Вывод',
    'withdrawProfit': 'Вывести прибыль',
    'withdrawalAmount': 'Сумма вывода',
    'availableForWithdrawal': 'Доступно для вывода',
    'withdrawAll': 'Вывести все',
    'selectCountry': 'Выберите страну',
    'chooseCountry': 'Выберите вашу страну',
    'searchCountries': 'Поиск стран...',
    'selectMethod': 'Выберите способ вывода',
    'bankCard': 'Банковская карта',
    'bankCardDesc': 'Вывод на банковскую карту',
    'mobilePayment': 'Мобильный платеж',
    'mobilePaymentDesc': 'СБП или перевод по номеру телефона',
    'cryptoPayment': 'Криптовалюта',
    'cryptoPaymentDesc': 'Вывод на криптокошелек',
    'enterPaymentDetails': 'Введите платежные реквизиты',
    'enterCardNumber': 'Введите номер карты',
    'enterPhoneNumber': 'Введите номер телефона',
    'enterCryptoAddress': 'Введите адрес кошелька (USDT TRC-20)',
    'amount': 'Сумма',
    'method': 'Способ',
    'reviewWithdrawal': 'Проверка и отправка',
    'submitWithdrawal': 'Отправить заявку на вывод',
    'submittingWithdrawal': 'Отправка...',
    'next': 'Далее',
    'back': 'Назад',
    'sberbankNotice': 'Переводы Сбербанка могут занять дополнительное время. Пожалуйста, подождите до 24 часов.',
    'withdrawalOnHold': 'Вывод на удержании',
    'withdrawalPending': 'Вывод в ожидании',
    'withdrawalCompleted': 'Вывод завершен',
    'contactSupport': 'Связаться с поддержкой',
    'noProfitYet': 'Пока нет прибыли',
    'clickToWithdraw': 'Нажмите для вывода',
    'completedInvestments': 'Завершенные инвестиции',
    'investmentPlusProfit': 'Инвестиция + Прибыль доступны',
    'activeProfit': 'Активная торговая прибыль',
    'profitOnlyWithdrawal': 'Только прибыль доступна для вывода',
    'noWithdrawalAvailable': 'Инвестиция еще в процессе.',
    'viewTransactionHistory': 'Посмотреть полную историю транзакций',
    'pendingWithdrawalExists': 'У вас уже есть заявка на вывод.',
    'withdrawn': 'Выведено',
    'cryptoWarning': 'Убедитесь, что только USDT депозит сделан по этому адресу.',
    'howToPayCrypto': 'Как сделать USDT платеж:',
    'cryptoStep1': 'Скопируйте адрес кошелька USDT выше',
    'cryptoStep2': 'Откройте криптокошелек и отправьте точную сумму USDT через сеть TRON (TRC20)',
    'cryptoStep3': 'Сделайте скриншот транзакции и отправьте подтверждение через WhatsApp',
    'cryptoStep4': 'Нажмите кнопку "Отправить заявку на инвестицию" ниже',
    'searchCountry': 'Поиск страны',
    'noCountriesFound': 'Страны не найдены',
    'countryRequired': 'Выберите страну для просмотра способов оплаты',
    'network': 'Сеть',
    'walletAddress': 'Адрес кошелька USDT',
    'amountToSend': 'Сумма для отправки',
    'important': 'Важно',
    'visionTitle': 'Инвестиционная возможность',
    'visionSubtitle': 'Почему умные инвесторы выбирают Tesla',
    'sustainableEnergy': 'Устойчивая энергия',
    'sustainableEnergyDesc': 'Ускорение перехода на возобновляемую энергию',
    'autonomousFuture': 'Автономное будущее',
    'autonomousFutureDesc': 'Технология автопилота меняет транспорт',
    'globalScale': 'Глобальный масштаб',
    'globalScaleDesc': 'Производственное совершенство с Гигафабриками',
    'whyInvest': 'Почему инвестировать в Tesla?',
    'sixReasons': 'Шесть причин выбрать Tesla для вашего портфеля',
    'reason1': 'Лидер рынка EV с долей более 20%',
    'reason2': 'Вертикально интегрированное производство',
    'reason3': 'Растущий бизнес хранения энергии',
    'reason4': 'Расширение возможностей ИИ',
    'reason5': 'Сильная лояльность бренда',
    'reason6': 'Глобальная экспансия',
    'getStartedToday': 'Начать сегодня',
    'downloadProspectus': 'Скачать проспект',
    'ceoQuote': 'Инвестируйте в будущее, где инновации сочетаются с устойчивой доходностью.',
    'testimonial1': 'Tesla Stock полностью преобразил мой инвестиционный портфель.',
    'testimonial2': 'Сначала я был скептически настроен, но после 6 месяцев стабильной прибыли я убедился.',
    'testimonial3': 'Прозрачность и профессионализм Tesla Stock не имеют себе равных.',
    'testimonial4': 'Начал с небольшой инвестиции и значительно увеличил её.',
    'testimonial5': 'Лучшее инвестиционное решение в моей жизни.',
    'testimonial6': 'Платформа превзошла мои ожидания.',
    'holdBillingMessage': 'Сообщение об удержании/комиссии',
    'autoGenerateFee': 'Автогенерация комиссии',
    'quickTemplates': 'Быстрые шаблоны',
    'saveAndNotify': 'Сохранить и уведомить',
    'securityLogs': 'Журналы безопасности',
    'loginAttempts': 'Попытки входа',
    'refreshLogs': 'Обновить',
    'success': 'Успешно',
    'failed': 'Неудачно',
    'userAgent': 'User Agent',
    'securityInfo': 'Информация о безопасности',
    'emailMonitoring': 'Мониторинг email',
    'user': 'Пользователь',
    'date': 'Дата',
    'country': 'Страна',
    'paymentDetailsLabel': 'Платежные реквизиты',
    'holdMessage': 'Сообщение удержания',
    'referralSettings': 'Настройки рефералов',
    'referralEmail': 'Email для уведомлений',
    'saveReferralSettings': 'Сохранить настройки рефералов',
  },
  // Danish (da)
  da: {
    'home': 'Hjem', 'about': 'Om os', 'investments': 'Investeringer', 'security': 'Sikkerhed', 'dashboard': 'Dashboard',
    'invest': 'Invester', 'signOut': 'Log ud', 'admin': 'Admin',
    'totalInvested': 'Total investeret', 'totalProfit': 'Total profit', 'pending': 'Afventende', 'active': 'Aktiv',
    'marketCap': 'Markedsværdi', 'stockPrice': 'Aktiekurs', 'globalDeliveries': 'Globale leveringer', 'superchargers': 'Superchargere',
    'makeNewInvestment': 'Lav ny investering', 'investmentAmount': 'Investeringsbeløb (USD)', 'enterAmount': 'Indtast beløb (min $100)',
    'submitInvestment': 'Indsend investeringsanmodning', 'processingText': 'Behandler...', 'minInvestment': 'Minimum investering er $100',
    'investmentSubmitted': 'Investeringsanmodning indsendt!', 'loadingPayment': 'Indlæser betalingsoplysninger...',
    'paymentDetails': 'Betalingsoplysninger', 'bankName': 'Banknavn', 'accountHolder': 'Kontohaver', 'cardNumber': 'Kortnummer',
    'copied': 'Kopieret!', 'walletCopied': 'Tegnebogsadresse kopieret!', 'investmentHistory': 'Investeringshistorik',
    'noInvestments': 'Ingen investeringer endnu. Start din rejse i dag!', 'profit': 'profit',
    'performanceChart': 'Investeringsperformance', 'teslaStock': 'Tesla aktieperformance',
    'signIn': 'Log ind', 'signUp': 'Tilmeld', 'email': 'Email', 'password': 'Adgangskode', 'fullName': 'Fulde navn',
    'welcomeBack': 'Velkommen tilbage', 'createAccount': 'Opret konto', 'forgotPassword': 'Glemt adgangskode?',
    'heroTitle': 'Invester i', 'heroTitleHighlight': 'Fremtidens elektriske mobilitet',
    'heroSubtitle': 'Handel og spor Tesla aktier i realtid. Deltag sammen med tusindvis af investorer.',
    'getStarted': 'Kom i gang', 'learnMore': 'Læs mere',
    'language': 'Sprog', 'english': 'English', 'russian': 'Русский', 'danish': 'Dansk',
    'footerDescription': 'Tesla Stock er en førende investeringsplatform specialiseret i EV aktier.',
    'company': 'Virksomhed', 'aboutUs': 'Om os', 'ourTeam': 'Vores team', 'careers': 'Karriere', 'contact': 'Kontakt',
    'legal': 'Juridisk', 'termsOfService': 'Servicevilkår', 'privacyPolicy': 'Privatlivspolitik',
    'withdraw': 'Udbetaling', 'withdrawProfit': 'Udbetal profit', 'withdrawalAmount': 'Udbetalingsbeløb',
    'availableForWithdrawal': 'Tilgængelig til udbetaling', 'withdrawAll': 'Udbetal alt',
    'selectCountry': 'Vælg dit land', 'chooseCountry': 'Vælg land', 'searchCountries': 'Søg lande...',
    'selectMethod': 'Vælg udbetalingsmetode', 'bankCard': 'Bankkort', 'bankCardDesc': 'Udbetal til bankkort',
    'cryptoPayment': 'Kryptovaluta', 'cryptoPaymentDesc': 'Udbetal til kryptotegnebog',
    'submitWithdrawal': 'Indsend udbetalingsanmodning', 'next': 'Næste', 'back': 'Tilbage',
    'withdrawalOnHold': 'Udbetaling på hold', 'withdrawalPending': 'Udbetaling afventer', 'withdrawalCompleted': 'Udbetaling gennemført',
    'contactSupport': 'Kontakt support', 'portfolioBalance': 'Porteføljebalance', 'noBalanceYet': 'Ingen balance endnu',
    'cryptoWarning': 'Sørg for at kun USDT indbetales via denne adresse.', 'searchCountry': 'Søg land',
    'network': 'Netværk', 'walletAddress': 'USDT tegnebogsadresse', 'amountToSend': 'Beløb at sende', 'important': 'Vigtigt',
    'referralCode': 'Henvisningskode', 'enterReferralCode': 'Indtast henvisningskode', 'optional': 'valgfri',
    'invalidReferralCode': 'Ugyldig henvisningskode.', 'testimonialTitle': 'Hvad vores investorer siger',
    'investor': 'Investor', 'marketLeader': 'Markedsleder', 'stockGrowthTitle': 'Tesla aktier:', 'exponentialGrowth': 'Eksponentiel vækst',
    'whyChooseUs': 'Hvorfor vælge os', 'featuresTitle': 'Alt hvad du behøver for at investere',
    'featureSecurity': 'Bankniveau sikkerhed', 'featureInstant': 'Øjeblikkelige transaktioner',
    'howItWorks': 'Sådan virker det', 'step': 'Trin',
    'faqTitle': 'Ofte stillede', 'faqTitleHighlight': 'spørgsmål', 'support': 'Support',
    'visionTitle': 'Investeringsmuligheden', 'sustainableEnergy': 'Bæredygtig energi', 'autonomousFuture': 'Autonom fremtid',
    'whyInvest': 'Hvorfor investere i Tesla?', 'getStartedToday': 'Kom i gang i dag',
  },
  // Estonian (et)
  et: {
    'home': 'Avaleht', 'about': 'Meist', 'investments': 'Investeeringud', 'security': 'Turvalisus', 'dashboard': 'Töölaud',
    'invest': 'Investeeri', 'signOut': 'Logi välja', 'admin': 'Admin',
    'totalInvested': 'Kokku investeeritud', 'totalProfit': 'Kogukasum', 'pending': 'Ootel', 'active': 'Aktiivne',
    'makeNewInvestment': 'Tee uus investeering', 'investmentAmount': 'Investeeringusumma (USD)', 'enterAmount': 'Sisesta summa (min $100)',
    'submitInvestment': 'Esita investeerimistaotlus', 'processingText': 'Töötlemine...', 'minInvestment': 'Minimaalne investeering on $100',
    'investmentSubmitted': 'Investeerimistaotlus esitatud!', 'loadingPayment': 'Makseteabe laadimine...',
    'paymentDetails': 'Makseteave', 'bankName': 'Panga nimi', 'cardNumber': 'Kaardi number',
    'copied': 'Kopeeritud!', 'walletCopied': 'Rahakoti aadress kopeeritud!', 'investmentHistory': 'Investeeringute ajalugu',
    'noInvestments': 'Investeeringuid pole veel. Alusta oma teekonda täna!', 'profit': 'kasum',
    'teslaStock': 'Tesla aktsia tulemuslikkus', 'signIn': 'Logi sisse', 'signUp': 'Registreeru',
    'email': 'E-post', 'password': 'Parool', 'fullName': 'Täisnimi', 'welcomeBack': 'Tere tulemast tagasi',
    'createAccount': 'Loo konto', 'forgotPassword': 'Unustasid parooli?',
    'heroTitle': 'Investeeri', 'heroTitleHighlight': 'Elektrimobiilsuse tulevikku',
    'heroSubtitle': 'Kaubelge ja jälgige Tesla aktsiaid reaalajas.',
    'getStarted': 'Alusta', 'learnMore': 'Loe lähemalt', 'language': 'Keel', 'estonian': 'Eesti',
    'footerDescription': 'Tesla Stock on esmaklassiline investeerimisplatvorm.',
    'company': 'Ettevõte', 'aboutUs': 'Meist', 'contact': 'Kontakt',
    'withdraw': 'Väljavõtmine', 'withdrawProfit': 'Võta kasum välja', 'withdrawalAmount': 'Väljavõtmise summa',
    'availableForWithdrawal': 'Saadaval väljavõtmiseks', 'withdrawAll': 'Võta kõik välja',
    'selectCountry': 'Vali oma riik', 'chooseCountry': 'Vali riik', 'searchCountries': 'Otsi riike...', 'searchCountry': 'Otsi riiki...',
    'bankCard': 'Pangakaart', 'cryptoPayment': 'Krüptovaluuta', 'submitWithdrawal': 'Esita väljavõtmistaotlus',
    'next': 'Järgmine', 'back': 'Tagasi', 'contactSupport': 'Võta ühendust toega',
    'portfolioBalance': 'Portfelli saldo', 'noBalanceYet': 'Saldot pole veel',
    'cryptoWarning': 'Veenduge, et ainult USDT sissemakse tehakse sellel aadressil.',
    'network': 'Võrk', 'walletAddress': 'USDT rahakoti aadress', 'amountToSend': 'Saadetav summa', 'important': 'Oluline',
    'referralCode': 'Soovituskood', 'optional': 'valikuline', 'invalidReferralCode': 'Vigane soovituskood.',
    'testimonialTitle': 'Mida ütlevad meie investorid', 'investor': 'Investor',
    'whyChooseUs': 'Miks valida meid', 'howItWorks': 'Kuidas see töötab',
    'faqTitle': 'Korduma kippuvad', 'faqTitleHighlight': 'küsimused', 'support': 'Tugi',
    'whyInvest': 'Miks investeerida Teslasse?', 'getStartedToday': 'Alusta täna',
  },
  // Finnish (fi)
  fi: {
    'home': 'Etusivu', 'about': 'Tietoja', 'investments': 'Sijoitukset', 'security': 'Turvallisuus', 'dashboard': 'Kojelauta',
    'invest': 'Sijoita', 'signOut': 'Kirjaudu ulos', 'admin': 'Ylläpito',
    'totalInvested': 'Sijoitettu yhteensä', 'totalProfit': 'Kokonaisvoitto', 'pending': 'Odottaa', 'active': 'Aktiivinen',
    'makeNewInvestment': 'Tee uusi sijoitus', 'investmentAmount': 'Sijoitussumma (USD)', 'enterAmount': 'Syötä summa (min $100)',
    'submitInvestment': 'Lähetä sijoituspyyntö', 'processingText': 'Käsitellään...', 'minInvestment': 'Minimisijoitus on $100',
    'investmentSubmitted': 'Sijoituspyyntö lähetetty!', 'loadingPayment': 'Ladataan maksutietoja...',
    'paymentDetails': 'Maksutiedot', 'bankName': 'Pankin nimi', 'cardNumber': 'Korttinumero',
    'copied': 'Kopioitu!', 'walletCopied': 'Lompakko-osoite kopioitu!', 'investmentHistory': 'Sijoitushistoria',
    'noInvestments': 'Ei sijoituksia vielä. Aloita matkasi tänään!', 'profit': 'voitto',
    'teslaStock': 'Teslan osakkeen kehitys', 'signIn': 'Kirjaudu sisään', 'signUp': 'Rekisteröidy',
    'email': 'Sähköposti', 'password': 'Salasana', 'fullName': 'Koko nimi', 'welcomeBack': 'Tervetuloa takaisin',
    'createAccount': 'Luo tili', 'forgotPassword': 'Unohditko salasanan?',
    'heroTitle': 'Sijoita', 'heroTitleHighlight': 'Sähköisen liikkumisen tulevaisuuteen',
    'heroSubtitle': 'Käy kauppaa ja seuraa Teslan osakkeita reaaliajassa.',
    'getStarted': 'Aloita', 'learnMore': 'Lue lisää', 'language': 'Kieli', 'finnish': 'Suomi',
    'footerDescription': 'Tesla Stock on johtava sijoitusalusta EV-osakkeisiin.',
    'company': 'Yritys', 'aboutUs': 'Tietoja meistä', 'contact': 'Yhteystiedot',
    'withdraw': 'Nosto', 'withdrawProfit': 'Nosta voitto', 'withdrawalAmount': 'Nostosumma',
    'availableForWithdrawal': 'Nostettavissa', 'withdrawAll': 'Nosta kaikki',
    'selectCountry': 'Valitse maasi', 'chooseCountry': 'Valitse maa', 'searchCountries': 'Etsi maita...',
    'bankCard': 'Pankkikortti', 'cryptoPayment': 'Kryptovaluutta', 'submitWithdrawal': 'Lähetä nostopyyntö',
    'next': 'Seuraava', 'back': 'Takaisin', 'contactSupport': 'Ota yhteyttä tukeen',
    'portfolioBalance': 'Salkun saldo', 'noBalanceYet': 'Ei saldoa vielä',
    'cryptoWarning': 'Varmista, että vain USDT-talletus tehdään tähän osoitteeseen.',
    'network': 'Verkko', 'walletAddress': 'USDT-lompakko-osoite', 'amountToSend': 'Lähetettävä summa', 'important': 'Tärkeää',
    'referralCode': 'Viittauskoodi', 'optional': 'valinnainen', 'invalidReferralCode': 'Virheellinen viittauskoodi.',
    'testimonialTitle': 'Mitä sijoittajamme sanovat', 'investor': 'Sijoittaja',
    'whyChooseUs': 'Miksi valita meidät', 'howItWorks': 'Näin se toimii',
    'faqTitle': 'Usein kysytyt', 'faqTitleHighlight': 'kysymykset', 'support': 'Tuki',
    'whyInvest': 'Miksi sijoittaa Teslaan?', 'getStartedToday': 'Aloita tänään',
  },
  // Dutch (nl) - Complete translations
  nl: {
    // Navigation
    'home': 'Home', 'about': 'Over ons', 'investments': 'Investeringen', 'security': 'Beveiliging', 'dashboard': 'Dashboard',
    'invest': 'Investeren', 'signOut': 'Uitloggen', 'admin': 'Admin',
    // Stats
    'totalInvested': 'Totaal geïnvesteerd', 'totalProfit': 'Totale winst', 'pending': 'In behandeling', 'active': 'Actief',
    'marketCap': 'Marktkapitalisatie', 'stockPrice': 'Aandelenkoers', 'globalDeliveries': 'Wereldwijde leveringen', 'superchargers': 'Superchargers',
    // Investment Form
    'makeNewInvestment': 'Nieuwe investering', 'investmentAmount': 'Investeringsbedrag (USD)', 'enterAmount': 'Voer bedrag in (min $100)',
    'submitInvestment': 'Investering indienen', 'processingText': 'Verwerken...', 'minInvestment': 'Minimale investering is $100',
    'investmentSubmitted': 'Investeringsaanvraag ingediend! Ons team neemt spoedig contact met u op.', 'loadingPayment': 'Betalingsgegevens laden...',
    'contactViaWhatsapp': 'Ons team neemt via WhatsApp contact met u op om de investering te voltooien',
    // Payment
    'paymentDetails': 'Betalingsgegevens', 'investmentDetails': 'Investeringsgegevens', 'bankName': 'Banknaam', 'accountHolder': 'Rekeninghouder', 'cardNumber': 'Kaartnummer',
    'copied': 'Gekopieerd!', 'walletCopied': 'Portemonnee-adres gekopieerd!', 'sendReceiptVia': 'Stuur betaalbewijs via WhatsApp na overboeking',
    'dashboardSubtitle': 'Beheer uw investeringen en volg uw winsten',
    // History
    'investmentHistory': 'Investeringsgeschiedenis', 'noInvestments': 'Nog geen investeringen. Begin vandaag uw reis!', 'profit': 'winst',
    'performanceChart': 'Investeringsprestaties', 'teslaStock': 'Tesla aandelenprestaties',
    // Notifications
    'profitNotification': 'Nieuwe winst ontvangen!', 'profitMessage': 'Uw investering heeft verdiend',
    // Auth
    'signIn': 'Inloggen', 'signUp': 'Registreren', 'email': 'E-mail', 'password': 'Wachtwoord', 'fullName': 'Volledige naam',
    'welcomeBack': 'Welkom terug', 'createAccount': 'Account aanmaken', 'forgotPassword': 'Wachtwoord vergeten?',
    'resetPassword': 'Wachtwoord resetten', 'enterPhone': 'Voer uw geregistreerde telefoonnummer in', 'phoneNumber': 'Telefoonnummer',
    'newPassword': 'Nieuw wachtwoord', 'confirmPassword': 'Bevestig wachtwoord', 'passwordChanged': 'Wachtwoord succesvol gewijzigd!',
    'invalidPhone': 'Ongeldig telefoonnummer', 'backToLogin': 'Terug naar inloggen',
    'signInSubtitle': 'Log in om toegang te krijgen tot uw account', 'createAccountSubtitle': 'Maak een account aan om te beginnen',
    'continueWithGoogle': 'Doorgaan met Google', 'connecting': 'Verbinden...', 'or': 'of',
    'enterFullName': 'Voer uw volledige naam in', 'enterEmail': 'Voer uw e-mailadres in', 'enterPassword': 'Voer uw wachtwoord in',
    'noAccount': 'Geen account? ', 'alreadyHaveAccount': 'Heeft u al een account? ',
    'termsAgreement': 'Door verder te gaan gaat u akkoord met onze Servicevoorwaarden en Privacybeleid',
    // Hero
    'heroTitle': 'Investeer in de', 'heroTitleHighlight': 'Toekomst van elektrische mobiliteit',
    'heroSubtitle': 'Handel en volg Tesla-aandelen in realtime. Sluit u aan bij duizenden investeerders die profiteren van Tesla\'s revolutionaire groei.',
    'getStarted': 'Begin nu', 'learnMore': 'Meer informatie',
    // Language
    'language': 'Taal', 'dutch': 'Nederlands', 'english': 'English', 'russian': 'Русский', 'french': 'Français', 'german': 'Deutsch', 'spanish': 'Español',
    // Footer
    'footerDescription': 'Tesla Stock is een toonaangevend investeringsplatform gespecialiseerd in elektrische voertuig- en duurzame energie-aandelen. Wij bieden veilige, transparante en winstgevende investeringsmogelijkheden.',
    'company': 'Bedrijf', 'aboutUs': 'Over ons', 'ourTeam': 'Ons team', 'careers': 'Carrières', 'contact': 'Contact',
    'legal': 'Juridisch', 'termsOfService': 'Servicevoorwaarden', 'privacyPolicy': 'Privacybeleid', 'riskDisclosure': 'Risico-informatie', 'cookiePolicy': 'Cookiebeleid',
    'regulatory': 'Regelgeving', 'license': 'Licentie', 'compliance': 'Compliance', 'amlPolicy': 'AML-beleid', 'investorProtection': 'Beleggersbescherming',
    'regulatedEntity': 'Gereguleerd investeringsplatform', 'licenseNumber': 'Licentienummer', 'allRightsReserved': 'Alle rechten voorbehouden.',
    'registrationInfo': 'Geregistreerd in Californië, VS. Registratienummer 2024-INV-001234',
    // Testimonials
    'testimonialTitle': 'Wat onze investeerders zeggen', 'testimonialSubtitle': 'Sluit u aan bij duizenden tevreden investeerders wereldwijd', 'investor': 'Investeerder',
    'testimonial1': 'Tesla Stock heeft mijn investeringsportefeuille volledig getransformeerd. De rendementen waren uitzonderlijk en het platform is ongelooflijk gebruiksvriendelijk.',
    'testimonial2': 'Ik was eerst sceptisch, maar na 6 maanden consistente winsten ben ik nu overtuigd. Sterk aanbevolen voor iedereen die in de toekomst wil investeren.',
    'testimonial3': 'De transparantie en professionaliteit van Tesla Stock zijn ongeëvenaard. Ik voel me veilig wetende dat mijn investeringen in goede handen zijn.',
    'testimonial4': 'Begonnen met een kleine investering en heb deze aanzienlijk laten groeien. De realtime tracking en winstmeldingen zijn fantastisch.',
    'testimonial5': 'De beste investeringsbeslissing die ik ooit heb gemaakt. Het team reageert snel en het platform doet wat het belooft.',
    'testimonial6': 'Het platform heeft mijn verwachtingen overtroffen. Realtime tracking en deskundige marktinzichten hebben me geholpen slimmere investeringsbeslissingen te nemen.',
    'ceoQuote': 'Investeer in de toekomst waar innovatie samengaat met duurzame rendementen. Tesla-aandelen vertegenwoordigen de convergentie van technologie, schone energie en ongekende marktgroei.',
    // Stock Growth
    'marketLeader': 'Marktleider', 'stockGrowthTitle': 'Tesla-aandelen:', 'exponentialGrowth': 'Exponentiële groei',
    'stockGrowthDesc': 'Tesla heeft consequent beter gepresteerd dan de markt en uitzonderlijke rendementen geleverd aan vroege investeerders. Sluit u vandaag aan bij de beweging.',
    'yearToDate': 'Jaar tot nu toe', 'fiveYear': '5 jaar rendement', 'sinceIPO': 'Sinds IPO',
    // Withdrawal
    'withdraw': 'Opnemen', 'withdrawProfit': 'Winst opnemen', 'withdrawalAmount': 'Opnamebedrag',
    'availableForWithdrawal': 'Beschikbaar voor opname', 'withdrawAll': 'Alles opnemen',
    'selectCountry': 'Selecteer uw land', 'chooseCountry': 'Kies land', 'searchCountries': 'Zoek landen...', 'searchCountry': 'Zoek land...',
    'selectMethod': 'Selecteer opnamemethode', 'bankCard': 'Bankkaart', 'bankCardDesc': 'Opnemen naar uw bankkaart',
    'mobilePayment': 'Mobiele betaling', 'mobilePaymentDesc': 'SBP of telefoonnummer overboeking',
    'cryptoPayment': 'Cryptocurrency', 'cryptoPaymentDesc': 'Opnemen naar crypto-portemonnee',
    'enterPaymentDetails': 'Voer betalingsgegevens in', 'enterCardNumber': 'Voer uw kaartnummer in',
    'enterPhoneNumber': 'Voer uw telefoonnummer in', 'enterCryptoAddress': 'Voer portemonnee-adres in (USDT TRC-20)',
    'amount': 'Bedrag', 'method': 'Methode', 'reviewWithdrawal': 'Bekijken & Indienen',
    'submitWithdrawal': 'Opnameaanvraag indienen', 'submittingWithdrawal': 'Indienen...', 'next': 'Volgende', 'back': 'Terug',
    'withdrawalOnHold': 'Opname in de wacht', 'withdrawalPending': 'Opname in behandeling', 'withdrawalCompleted': 'Opname voltooid',
    'contactSupport': 'Neem contact op met ondersteuning', 'noProfitYet': 'Nog geen winst', 'clickToWithdraw': 'Klik om op te nemen',
    'completedInvestments': 'Voltooide investeringen', 'investmentPlusProfit': 'Investering + Winst beschikbaar',
    'activeProfit': 'Actieve handelswinst', 'profitOnlyWithdrawal': 'Alleen winst opneembaar tijdens handel',
    'noWithdrawalAvailable': 'Investering nog in uitvoering. Opname beschikbaar na voltooiing van de handel.',
    'viewTransactionHistory': 'Bekijk volledige transactiegeschiedenis', 'pendingWithdrawalExists': 'U heeft al een lopende opnameaanvraag. Wacht tot deze is verwerkt.',
    'withdrawn': 'Opgenomen', 'noCountriesFound': 'Geen landen gevonden',
    // Portfolio
    'portfolioBalance': 'Portefeuillesaldo', 'noBalanceYet': 'Nog geen saldo', 'investment': 'Investering',
    'investmentSteps': 'Stappen om de investering te voltooien:', 'step1': 'Betaal naar bovenstaande rekeninggegevens', 'step2': 'Stuur betaalbewijs via WhatsApp', 'step3': 'Klik op "Investering indienen"',
    // Crypto
    'cryptoWarning': 'Zorg ervoor dat alleen USDT wordt gestort via dit adres. Anders wordt uw investering niet geactiveerd.',
    'howToPayCrypto': 'Hoe USDT-betaling te doen:', 'cryptoStep1': 'Kopieer het bovenstaande USDT-portemonnee-adres',
    'network': 'Netwerk', 'walletAddress': 'USDT portemonnee-adres', 'amountToSend': 'Te versturen bedrag', 'important': 'Belangrijk',
    // Referral
    'referralCode': 'Verwijzingscode', 'enterReferralCode': 'Voer verwijzingscode in', 'optional': 'optioneel',
    'invalidReferralCode': 'Ongeldige verwijzingscode. Controleer en probeer opnieuw.',
    'referralSettings': 'Verwijzingsinstellingen', 'referralEmail': 'Notificatie-e-mail', 'saveReferralSettings': 'Verwijzingsinstellingen opslaan',
    // Vision
    'visionTitle': 'De investeringsmogelijkheid', 'visionSubtitle': 'Waarom slimme investeerders kiezen voor Tesla voor exponentiële portefeuillegroei',
    'sustainableEnergy': 'Duurzame energie', 'sustainableEnergyDesc': 'De overgang van de wereld naar hernieuwbare energie versnellen',
    'autonomousFuture': 'Autonome toekomst', 'autonomousFutureDesc': 'Volledige zelfrijdende technologie verandert het transport',
    'globalScale': 'Wereldwijde schaal', 'globalScaleDesc': 'Productie-uitmuntendheid met Gigafabrieken wereldwijd',
    // Why Invest
    'whyInvest': 'Waarom investeren in Tesla?', 'sixReasons': 'Zes overtuigende redenen om Tesla voor uw portefeuille te overwegen',
    'reason1': 'Marktleider in EV-industrie met 20%+ marktaandeel', 'reason2': 'Verticaal geïntegreerde productie die kosten verlaagt',
    'reason3': 'Groeiende energieopslag- en zonneactiviteiten', 'reason4': 'Uitbreiding van AI en autonome rijmogelijkheden',
    'reason5': 'Sterke merkloyaliteit en klanttevredenheid', 'reason6': 'Wereldwijde expansie met nieuwe Gigafabrieken',
    'getStartedToday': 'Begin vandaag', 'downloadProspectus': 'Download prospectus',
    // Features
    'whyChooseUs': 'Waarom voor ons kiezen', 'featuresTitle': 'Alles wat u nodig heeft om te investeren',
    'featuresSubtitle': 'Een compleet platform ontworpen voor zowel beginners als ervaren investeerders.',
    'featureSecurity': 'Beveiliging op bankniveau', 'featureSecurityDesc': 'Uw investeringen worden beschermd met 256-bit encryptie en multi-factor authenticatie.',
    'featureInstant': 'Directe transacties', 'featureInstantDesc': 'Voer transacties uit in milliseconden met onze high-performance handelsinfrastructuur.',
    'featureMobile': 'Mobiel geoptimaliseerd', 'featureMobileDesc': 'Volledige handelservaring op elk apparaat, overal ter wereld.',
    'featureAnalytics': 'Realtime analyses', 'featureAnalyticsDesc': 'Volg uw portefeuilleprestaties met live grafieken en gedetailleerde inzichten.',
    'featureWithdrawals': 'Snelle opnames', 'featureWithdrawalsDesc': 'Toegang tot uw fondsen binnen 24 uur via bankoverschrijving of cryptocurrency.',
    'featureSupport': '24/7 Ondersteuning', 'featureSupportDesc': 'Toegewijd ondersteuningsteam 24 uur per dag beschikbaar om u te helpen.',
    // How It Works
    'gettingStarted': 'Aan de slag', 'howItWorks': 'Hoe het werkt', 'howItWorksSubtitle': 'Begin uw investeringsreis in vier eenvoudige stappen.',
    'step': 'Stap', 'howStep1Title': 'Maak uw account aan', 'howStep1Desc': 'Meld u aan in minder dan 2 minuten met uw e-mail. Verificatie is snel en veilig.',
    'howStep2Title': 'Vul uw portemonnee', 'howStep2Desc': 'Stort fondsen via bankoverschrijving, creditcard of cryptocurrency.',
    'howStep3Title': 'Investeer in Tesla', 'howStep3Desc': 'Koop Tesla-aandelen vanaf slechts $100 met directe bevestiging.',
    'howStep4Title': 'Groei & Opnemen', 'howStep4Desc': 'Zie uw investering groeien en neem winsten op wanneer u wilt.',
    // Innovations
    'innovationsTitle': 'Leidende innovatie', 'innovationsSubtitle': 'Tesla\'s technologische doorbraken veranderen hele industrieën',
    'innovationBattery': 'Batterijtechnologie', 'innovationBatteryDesc': 'Revolutionaire 4680-cellen die langer bereik, sneller opladen en lagere kosten leveren',
    'innovationBatteryStat': '500+ mijl bereik', 'innovationAI': 'AI & Volledig zelfrijdend',
    'innovationAIDesc': 'Neurale netwerken verwerken real-world data om autonoom rijden te bereiken', 'innovationAIStat': '150M+ gereden mijlen',
    'innovationSupercharger': 'Wereldwijd Supercharger-netwerk', 'innovationSuperchargerDesc': 'Het snelste EV-laadnetwerk ter wereld met strategische wereldwijde dekking',
    'innovationSuperchargerStat': '50K+ stations', 'innovationSpaceX': 'SpaceX-synergie',
    'innovationSpaceXDesc': 'Kruisinnovatie tussen Tesla en SpaceX die baanbrekende technologieën aandrijft', 'innovationSpaceXStat': 'Multi-planetaire visie',
    // FAQ
    'support': 'Ondersteuning', 'faqTitle': 'Veelgestelde', 'faqTitleHighlight': 'vragen',
    'faqSubtitle': 'Heeft u vragen? Wij hebben antwoorden. Vind alles wat u moet weten over investeren bij ons.',
    'faqQuestion1': 'Is dit het echte Tesla-aandeel?', 'faqAnswer1': 'Ja, wij bieden toegang tot echte Tesla (TSLA) aandelenInvesteringen via gereguleerde en gelicentieerde financiële partners. Uw investeringen worden ondersteund door daadwerkelijke Tesla-aandelen die worden verhandeld op grote effectenbeurzen.',
    'faqQuestion2': 'Hoe veilig zijn mijn investeringen?', 'faqAnswer2': 'Uw investeringen worden beschermd door SSL-encryptie op bankniveau en opgeslagen op beveiligde, gereguleerde rekeningen. Wij gebruiken multi-factor authenticatie, geavanceerde fraudedetectie en cold storage voor activa.',
    'faqQuestion3': 'Hoe neem ik mijn winsten op?', 'faqAnswer3': 'Opnemen is eenvoudig! Ga naar uw Dashboard, klik op "Fondsen opnemen", voer het bedrag in dat u wilt opnemen, selecteer uw gewenste betaalmethode en dien uw aanvraag in.',
    'faqQuestion4': 'Wat is het minimale investeringsbedrag?', 'faqAnswer4': 'U kunt beginnen met investeren vanaf slechts $100. Deze lage instapdrempel maakt Tesla-aandelen toegankelijk voor iedereen.',
    // Admin
    'adminPanel': 'Beheerderspaneel', 'paymentSettings': 'Betalingsinstellingen', 'withdrawalSettings': 'Opname-instellingen',
    'supportSettings': 'Klantenondersteuning instellingen', 'savePaymentSettings': 'Betalingsinstellingen opslaan',
    'saveWithdrawalSettings': 'Opname-instellingen opslaan', 'saveSupportSettings': 'Ondersteuningsinstellingen opslaan',
    'noInvestmentsYet': 'Nog geen investeringen', 'noWithdrawalsYet': 'Nog geen opnames',
    'setProfit': 'Winst instellen', 'sendProfitEmail': 'Winst-e-mail versturen', 'approve': 'Goedkeuren', 'cancel': 'Annuleren',
    'complete': 'Voltooien', 'processing': 'Verwerken', 'hold': 'In de wacht', 'editMessage': 'Bericht bewerken',
    'setPending': 'In behandeling zetten', 'putOnHold': 'In de wacht zetten', 'setProcessing': 'Verwerken instellen',
    'holdBillingMessage': 'Wacht/Factureringskosten bericht', 'autoGenerateFee': 'Automatisch kosten genereren',
    'quickTemplates': 'Snelle sjablonen', 'saveAndNotify': 'Opslaan & Melden',
    'securityLogs': 'Beveiligingslogboeken', 'loginAttempts': 'Inlogpogingen', 'refreshLogs': 'Vernieuwen',
    'success': 'Succes', 'failed': 'Mislukt', 'userAgent': 'User Agent', 'securityInfo': 'Beveiligingsinformatie',
    'emailMonitoring': 'E-mailmonitoring', 'user': 'Gebruiker', 'date': 'Datum', 'country': 'Land',
    'paymentDetailsLabel': 'Betalingsgegevens', 'holdMessage': 'Wachtbericht',
    'defaultLanguage': 'Standaardtaal', 'setDefaultLanguage': 'Standaardtaal instellen',
    'adminPasscode': 'Voer beheerderswachtwoord in', 'accessDenied': 'Toegang geweigerd', 'enterPasscode': 'Voer wachtwoord in voor toegang tot beheerderspaneel',
  },
  // Norwegian (no)
  no: {
    'home': 'Hjem', 'about': 'Om oss', 'investments': 'Investeringer', 'security': 'Sikkerhet', 'dashboard': 'Dashbord',
    'invest': 'Invester', 'signOut': 'Logg ut', 'admin': 'Admin',
    'totalInvested': 'Totalt investert', 'totalProfit': 'Total fortjeneste', 'pending': 'Venter', 'active': 'Aktiv',
    'makeNewInvestment': 'Ny investering', 'investmentAmount': 'Investeringsbeløp (USD)', 'enterAmount': 'Skriv inn beløp (min $100)',
    'submitInvestment': 'Send investeringsforespørsel', 'processingText': 'Behandler...', 'minInvestment': 'Minimum investering er $100',
    'investmentSubmitted': 'Investeringsforespørsel sendt!', 'loadingPayment': 'Laster betalingsdetaljer...',
    'paymentDetails': 'Betalingsdetaljer', 'bankName': 'Banknavn', 'cardNumber': 'Kortnummer',
    'copied': 'Kopiert!', 'walletCopied': 'Lommebokadresse kopiert!', 'investmentHistory': 'Investeringshistorikk',
    'noInvestments': 'Ingen investeringer ennå. Start din reise i dag!', 'profit': 'fortjeneste',
    'teslaStock': 'Tesla aksjeutvikling', 'signIn': 'Logg inn', 'signUp': 'Registrer',
    'email': 'E-post', 'password': 'Passord', 'fullName': 'Fullt navn', 'welcomeBack': 'Velkommen tilbake',
    'createAccount': 'Opprett konto', 'forgotPassword': 'Glemt passord?',
    'heroTitle': 'Invester i', 'heroTitleHighlight': 'Fremtidens elektriske mobilitet',
    'heroSubtitle': 'Handle og spor Tesla-aksjer i sanntid.',
    'getStarted': 'Kom i gang', 'learnMore': 'Les mer', 'language': 'Språk', 'norwegian': 'Norsk',
    'footerDescription': 'Tesla Stock er en ledende investeringsplattform for EV-aksjer.',
    'company': 'Selskap', 'aboutUs': 'Om oss', 'contact': 'Kontakt',
    'withdraw': 'Uttak', 'withdrawProfit': 'Ta ut fortjeneste', 'withdrawalAmount': 'Uttaksbeløp',
    'availableForWithdrawal': 'Tilgjengelig for uttak', 'withdrawAll': 'Ta ut alt',
    'selectCountry': 'Velg ditt land', 'chooseCountry': 'Velg land', 'searchCountries': 'Søk land...', 'searchCountry': 'Søk land...',
    'bankCard': 'Bankkort', 'cryptoPayment': 'Kryptovaluta', 'submitWithdrawal': 'Send uttaksforespørsel',
    'next': 'Neste', 'back': 'Tilbake', 'contactSupport': 'Kontakt støtte',
    'portfolioBalance': 'Porteføljesaldo', 'noBalanceYet': 'Ingen saldo ennå',
    'cryptoWarning': 'Sørg for at kun USDT innskudd gjøres via denne adressen.',
    'network': 'Nettverk', 'walletAddress': 'USDT lommebokadresse', 'amountToSend': 'Beløp å sende', 'important': 'Viktig',
    'referralCode': 'Henvisningskode', 'optional': 'valgfritt', 'invalidReferralCode': 'Ugyldig henvisningskode.',
    'testimonialTitle': 'Hva våre investorer sier', 'investor': 'Investor',
    'whyChooseUs': 'Hvorfor velge oss', 'howItWorks': 'Slik fungerer det',
    'faqTitle': 'Ofte stilte', 'faqTitleHighlight': 'spørsmål', 'support': 'Støtte',
    'whyInvest': 'Hvorfor investere i Tesla?', 'getStartedToday': 'Kom i gang i dag',
  },
  // Slovak (sk)
  sk: {
    'home': 'Domov', 'about': 'O nás', 'investments': 'Investície', 'security': 'Bezpečnosť', 'dashboard': 'Prehľad',
    'invest': 'Investovať', 'signOut': 'Odhlásiť sa', 'admin': 'Admin',
    'totalInvested': 'Celkom investované', 'totalProfit': 'Celkový zisk', 'pending': 'Čakajúce', 'active': 'Aktívne',
    'makeNewInvestment': 'Nová investícia', 'investmentAmount': 'Suma investície (USD)', 'enterAmount': 'Zadajte sumu (min $100)',
    'submitInvestment': 'Odoslať investičnú požiadavku', 'processingText': 'Spracováva sa...', 'minInvestment': 'Minimálna investícia je $100',
    'investmentSubmitted': 'Investičná požiadavka odoslaná!', 'loadingPayment': 'Načítavanie platobných údajov...',
    'paymentDetails': 'Platobné údaje', 'bankName': 'Názov banky', 'cardNumber': 'Číslo karty',
    'copied': 'Skopírované!', 'walletCopied': 'Adresa peňaženky skopírovaná!', 'investmentHistory': 'História investícií',
    'noInvestments': 'Zatiaľ žiadne investície. Začnite svoju cestu ešte dnes!', 'profit': 'zisk',
    'teslaStock': 'Výkonnosť akcií Tesla', 'signIn': 'Prihlásiť sa', 'signUp': 'Registrovať sa',
    'email': 'E-mail', 'password': 'Heslo', 'fullName': 'Celé meno', 'welcomeBack': 'Vitajte späť',
    'createAccount': 'Vytvoriť účet', 'forgotPassword': 'Zabudli ste heslo?',
    'heroTitle': 'Investujte do', 'heroTitleHighlight': 'Budúcnosti elektrickej mobility',
    'heroSubtitle': 'Obchodujte a sledujte akcie Tesla v reálnom čase.',
    'getStarted': 'Začať', 'learnMore': 'Zistiť viac', 'language': 'Jazyk', 'slovak': 'Slovenčina',
    'footerDescription': 'Tesla Stock je popredná investičná platforma pre EV akcie.',
    'company': 'Spoločnosť', 'aboutUs': 'O nás', 'contact': 'Kontakt',
    'withdraw': 'Výber', 'withdrawProfit': 'Vybrať zisk', 'withdrawalAmount': 'Suma výberu',
    'availableForWithdrawal': 'K dispozícii na výber', 'withdrawAll': 'Vybrať všetko',
    'selectCountry': 'Vyberte krajinu', 'chooseCountry': 'Vyberte krajinu', 'searchCountries': 'Hľadať krajiny...', 'searchCountry': 'Hľadať krajinu...',
    'bankCard': 'Banková karta', 'cryptoPayment': 'Kryptomena', 'submitWithdrawal': 'Odoslať žiadosť o výber',
    'next': 'Ďalej', 'back': 'Späť', 'contactSupport': 'Kontaktovať podporu',
    'portfolioBalance': 'Zostatok portfólia', 'noBalanceYet': 'Zatiaľ žiadny zostatok',
    'cryptoWarning': 'Uistite sa, že na túto adresu je vložená iba USDT.',
    'network': 'Sieť', 'walletAddress': 'Adresa USDT peňaženky', 'amountToSend': 'Suma na odoslanie', 'important': 'Dôležité',
    'referralCode': 'Odporúčací kód', 'optional': 'voliteľné', 'invalidReferralCode': 'Neplatný odporúčací kód.',
    'testimonialTitle': 'Čo hovoria naši investori', 'investor': 'Investor',
    'whyChooseUs': 'Prečo si vybrať nás', 'howItWorks': 'Ako to funguje',
    'faqTitle': 'Často kladené', 'faqTitleHighlight': 'otázky', 'support': 'Podpora',
    'whyInvest': 'Prečo investovať do Tesly?', 'getStartedToday': 'Začnite ešte dnes',
  },
  // Slovenian (sl)
  sl: {
    'home': 'Domov', 'about': 'O nas', 'investments': 'Naložbe', 'security': 'Varnost', 'dashboard': 'Nadzorna plošča',
    'invest': 'Vloži', 'signOut': 'Odjava', 'admin': 'Admin',
    'totalInvested': 'Skupno vloženo', 'totalProfit': 'Skupni dobiček', 'pending': 'V čakanju', 'active': 'Aktivno',
    'makeNewInvestment': 'Nova naložba', 'investmentAmount': 'Znesek naložbe (USD)', 'enterAmount': 'Vnesite znesek (min $100)',
    'submitInvestment': 'Oddaj zahtevo za naložbo', 'processingText': 'Obdelava...', 'minInvestment': 'Minimalna naložba je $100',
    'investmentSubmitted': 'Zahteva za naložbo oddana!', 'loadingPayment': 'Nalaganje plačilnih podatkov...',
    'paymentDetails': 'Plačilni podatki', 'bankName': 'Ime banke', 'cardNumber': 'Številka kartice',
    'copied': 'Kopirano!', 'walletCopied': 'Naslov denarnice kopiran!', 'investmentHistory': 'Zgodovina naložb',
    'noInvestments': 'Še ni naložb. Začnite svojo pot danes!', 'profit': 'dobiček',
    'teslaStock': 'Uspešnost delnic Tesla', 'signIn': 'Prijava', 'signUp': 'Registracija',
    'email': 'E-pošta', 'password': 'Geslo', 'fullName': 'Polno ime', 'welcomeBack': 'Dobrodošli nazaj',
    'createAccount': 'Ustvari račun', 'forgotPassword': 'Pozabljeno geslo?',
    'heroTitle': 'Vložite v', 'heroTitleHighlight': 'Prihodnost električne mobilnosti',
    'heroSubtitle': 'Trgujte in spremljajte delnice Tesla v realnem času.',
    'getStarted': 'Začni', 'learnMore': 'Več informacij', 'language': 'Jezik', 'slovenian': 'Slovenščina',
    'footerDescription': 'Tesla Stock je vodilna naložbena platforma za EV delnice.',
    'company': 'Podjetje', 'aboutUs': 'O nas', 'contact': 'Kontakt',
    'withdraw': 'Dvig', 'withdrawProfit': 'Dvigni dobiček', 'withdrawalAmount': 'Znesek dviga',
    'availableForWithdrawal': 'Na voljo za dvig', 'withdrawAll': 'Dvigni vse',
    'selectCountry': 'Izberite državo', 'chooseCountry': 'Izberite državo', 'searchCountries': 'Išči države...', 'searchCountry': 'Išči državo...',
    'bankCard': 'Bančna kartica', 'cryptoPayment': 'Kriptovaluta', 'submitWithdrawal': 'Oddaj zahtevo za dvig',
    'next': 'Naprej', 'back': 'Nazaj', 'contactSupport': 'Kontaktiraj podporo',
    'portfolioBalance': 'Stanje portfelja', 'noBalanceYet': 'Še ni stanja',
    'cryptoWarning': 'Prepričajte se, da je na ta naslov položen samo USDT.',
    'network': 'Omrežje', 'walletAddress': 'Naslov USDT denarnice', 'amountToSend': 'Znesek za pošiljanje', 'important': 'Pomembno',
    'referralCode': 'Priporočilna koda', 'optional': 'neobvezno', 'invalidReferralCode': 'Neveljavna priporočilna koda.',
    'testimonialTitle': 'Kaj pravijo naši vlagatelji', 'investor': 'Vlagatelj',
    'whyChooseUs': 'Zakaj izbrati nas', 'howItWorks': 'Kako deluje',
    'faqTitle': 'Pogosto zastavljena', 'faqTitleHighlight': 'vprašanja', 'support': 'Podpora',
    'whyInvest': 'Zakaj vlagati v Teslo?', 'getStartedToday': 'Začni danes',
  },
  // Swedish (sv)
  sv: {
    'home': 'Hem', 'about': 'Om oss', 'investments': 'Investeringar', 'security': 'Säkerhet', 'dashboard': 'Översikt',
    'invest': 'Investera', 'signOut': 'Logga ut', 'admin': 'Admin',
    'totalInvested': 'Totalt investerat', 'totalProfit': 'Total vinst', 'pending': 'Väntande', 'active': 'Aktiv',
    'makeNewInvestment': 'Ny investering', 'investmentAmount': 'Investeringsbelopp (USD)', 'enterAmount': 'Ange belopp (min $100)',
    'submitInvestment': 'Skicka investeringsbegäran', 'processingText': 'Bearbetar...', 'minInvestment': 'Minsta investering är $100',
    'investmentSubmitted': 'Investeringsbegäran skickad!', 'loadingPayment': 'Laddar betalningsuppgifter...',
    'paymentDetails': 'Betalningsuppgifter', 'bankName': 'Banknamn', 'cardNumber': 'Kortnummer',
    'copied': 'Kopierat!', 'walletCopied': 'Plånboksadress kopierad!', 'investmentHistory': 'Investeringshistorik',
    'noInvestments': 'Inga investeringar ännu. Börja din resa idag!', 'profit': 'vinst',
    'teslaStock': 'Tesla aktieprestanda', 'signIn': 'Logga in', 'signUp': 'Registrera',
    'email': 'E-post', 'password': 'Lösenord', 'fullName': 'Fullständigt namn', 'welcomeBack': 'Välkommen tillbaka',
    'createAccount': 'Skapa konto', 'forgotPassword': 'Glömt lösenord?',
    'heroTitle': 'Investera i', 'heroTitleHighlight': 'Framtidens elektriska mobilitet',
    'heroSubtitle': 'Handla och spåra Tesla-aktier i realtid.',
    'getStarted': 'Kom igång', 'learnMore': 'Läs mer', 'language': 'Språk', 'swedish': 'Svenska',
    'footerDescription': 'Tesla Stock är en ledande investeringsplattform för EV-aktier.',
    'company': 'Företag', 'aboutUs': 'Om oss', 'contact': 'Kontakt',
    'withdraw': 'Uttag', 'withdrawProfit': 'Ta ut vinst', 'withdrawalAmount': 'Uttagsbelopp',
    'availableForWithdrawal': 'Tillgängligt för uttag', 'withdrawAll': 'Ta ut allt',
    'selectCountry': 'Välj ditt land', 'chooseCountry': 'Välj land', 'searchCountries': 'Sök länder...',
    'bankCard': 'Bankkort', 'cryptoPayment': 'Kryptovaluta', 'submitWithdrawal': 'Skicka uttagsbegäran',
    'next': 'Nästa', 'back': 'Tillbaka', 'contactSupport': 'Kontakta support',
    'portfolioBalance': 'Portföljsaldo', 'noBalanceYet': 'Inget saldo ännu',
    'cryptoWarning': 'Se till att endast USDT-insättning görs via denna adress.',
    'network': 'Nätverk', 'walletAddress': 'USDT plånboksadress', 'amountToSend': 'Belopp att skicka', 'important': 'Viktigt',
    'referralCode': 'Värvningskod', 'optional': 'valfritt', 'invalidReferralCode': 'Ogiltig värvningskod.',
    'testimonialTitle': 'Vad våra investerare säger', 'investor': 'Investerare',
    'whyChooseUs': 'Varför välja oss', 'howItWorks': 'Så fungerar det',
    'faqTitle': 'Vanliga', 'faqTitleHighlight': 'frågor', 'support': 'Support',
    'whyInvest': 'Varför investera i Tesla?', 'getStartedToday': 'Kom igång idag',
  },
  // Add remaining languages with core translations...
  fr: {
    'home': 'Accueil', 'about': 'À propos', 'investments': 'Investissements', 'security': 'Sécurité', 'dashboard': 'Tableau de bord',
    'invest': 'Investir', 'signOut': 'Déconnexion', 'admin': 'Admin',
    'totalInvested': 'Total investi', 'totalProfit': 'Profit total', 'pending': 'En attente', 'active': 'Actif',
    'makeNewInvestment': 'Nouvel investissement', 'investmentAmount': 'Montant (USD)', 'enterAmount': 'Entrez le montant (min $100)',
    'submitInvestment': 'Soumettre la demande', 'processingText': 'Traitement...', 'minInvestment': 'Investissement minimum $100',
    'paymentDetails': 'Détails de paiement', 'cardNumber': 'Numéro de carte', 'copied': 'Copié!', 'walletCopied': 'Adresse du portefeuille copiée!',
    'investmentHistory': 'Historique', 'noInvestments': 'Pas encore d\'investissements.', 'profit': 'profit',
    'teslaStock': 'Performance Tesla', 'signIn': 'Connexion', 'signUp': 'Inscription',
    'email': 'Email', 'password': 'Mot de passe', 'fullName': 'Nom complet', 'welcomeBack': 'Bienvenue',
    'heroTitle': 'Investissez dans', 'heroTitleHighlight': 'L\'avenir de la mobilité électrique',
    'getStarted': 'Commencer', 'learnMore': 'En savoir plus', 'language': 'Langue',
    'withdraw': 'Retrait', 'withdrawalAmount': 'Montant du retrait', 'selectCountry': 'Sélectionnez votre pays',
    'bankCard': 'Carte bancaire', 'cryptoPayment': 'Cryptomonnaie', 'submitWithdrawal': 'Soumettre le retrait',
    'next': 'Suivant', 'back': 'Retour', 'contactSupport': 'Contacter le support',
    'portfolioBalance': 'Solde du portefeuille', 'cryptoWarning': 'Assurez-vous que seul USDT est déposé.',
    'network': 'Réseau', 'walletAddress': 'Adresse du portefeuille USDT', 'important': 'Important',
    'referralCode': 'Code de parrainage', 'optional': 'optionnel',
  },
  de: {
    'home': 'Startseite', 'about': 'Über uns', 'investments': 'Investitionen', 'security': 'Sicherheit', 'dashboard': 'Dashboard',
    'invest': 'Investieren', 'signOut': 'Abmelden', 'admin': 'Admin',
    'totalInvested': 'Gesamt investiert', 'totalProfit': 'Gesamtgewinn', 'pending': 'Ausstehend', 'active': 'Aktiv',
    'makeNewInvestment': 'Neue Investition', 'investmentAmount': 'Investitionsbetrag (USD)', 'enterAmount': 'Betrag eingeben (min $100)',
    'submitInvestment': 'Investitionsanfrage senden', 'processingText': 'Wird verarbeitet...', 'minInvestment': 'Mindestinvestition ist $100',
    'paymentDetails': 'Zahlungsdetails', 'cardNumber': 'Kartennummer', 'copied': 'Kopiert!', 'walletCopied': 'Wallet-Adresse kopiert!',
    'investmentHistory': 'Investitionshistorie', 'noInvestments': 'Noch keine Investitionen.', 'profit': 'Gewinn',
    'teslaStock': 'Tesla Aktienperformance', 'signIn': 'Anmelden', 'signUp': 'Registrieren',
    'email': 'E-Mail', 'password': 'Passwort', 'fullName': 'Vollständiger Name', 'welcomeBack': 'Willkommen zurück',
    'heroTitle': 'Investieren Sie in die', 'heroTitleHighlight': 'Zukunft der Elektromobilität',
    'getStarted': 'Loslegen', 'learnMore': 'Mehr erfahren', 'language': 'Sprache',
    'withdraw': 'Auszahlung', 'withdrawalAmount': 'Auszahlungsbetrag', 'selectCountry': 'Wählen Sie Ihr Land',
    'bankCard': 'Bankkarte', 'cryptoPayment': 'Kryptowährung', 'submitWithdrawal': 'Auszahlung beantragen',
    'next': 'Weiter', 'back': 'Zurück', 'contactSupport': 'Support kontaktieren',
    'portfolioBalance': 'Portfolio-Saldo', 'cryptoWarning': 'Stellen Sie sicher, dass nur USDT eingezahlt wird.',
    'network': 'Netzwerk', 'walletAddress': 'USDT Wallet-Adresse', 'important': 'Wichtig',
    'referralCode': 'Empfehlungscode', 'optional': 'optional',
  },
  es: {
    'home': 'Inicio', 'about': 'Acerca de', 'investments': 'Inversiones', 'security': 'Seguridad', 'dashboard': 'Panel',
    'invest': 'Invertir', 'signOut': 'Cerrar sesión', 'admin': 'Admin',
    'totalInvested': 'Total invertido', 'totalProfit': 'Beneficio total', 'pending': 'Pendiente', 'active': 'Activo',
    'makeNewInvestment': 'Nueva inversión', 'investmentAmount': 'Monto de inversión (USD)', 'enterAmount': 'Ingrese monto (mín $100)',
    'submitInvestment': 'Enviar solicitud de inversión', 'processingText': 'Procesando...', 'minInvestment': 'Inversión mínima es $100',
    'paymentDetails': 'Detalles de pago', 'cardNumber': 'Número de tarjeta', 'copied': '¡Copiado!', 'walletCopied': '¡Dirección de billetera copiada!',
    'investmentHistory': 'Historial de inversiones', 'noInvestments': 'Sin inversiones aún.', 'profit': 'beneficio',
    'teslaStock': 'Rendimiento de acciones Tesla', 'signIn': 'Iniciar sesión', 'signUp': 'Registrarse',
    'email': 'Correo electrónico', 'password': 'Contraseña', 'fullName': 'Nombre completo', 'welcomeBack': 'Bienvenido de nuevo',
    'heroTitle': 'Invierte en el', 'heroTitleHighlight': 'Futuro de la movilidad eléctrica',
    'getStarted': 'Comenzar', 'learnMore': 'Saber más', 'language': 'Idioma',
    'withdraw': 'Retiro', 'withdrawalAmount': 'Monto de retiro', 'selectCountry': 'Seleccione su país',
    'bankCard': 'Tarjeta bancaria', 'cryptoPayment': 'Criptomoneda', 'submitWithdrawal': 'Enviar solicitud de retiro',
    'next': 'Siguiente', 'back': 'Atrás', 'contactSupport': 'Contactar soporte',
    'portfolioBalance': 'Saldo del portafolio', 'cryptoWarning': 'Asegúrese de depositar solo USDT.',
    'network': 'Red', 'walletAddress': 'Dirección de billetera USDT', 'important': 'Importante',
    'referralCode': 'Código de referido', 'optional': 'opcional',
  },
  zh: {
    'home': '首页', 'about': '关于我们', 'investments': '投资', 'security': '安全', 'dashboard': '仪表板',
    'invest': '投资', 'signOut': '登出', 'admin': '管理员',
    'totalInvested': '总投资', 'totalProfit': '总利润', 'pending': '待处理', 'active': '活跃',
    'makeNewInvestment': '新投资', 'investmentAmount': '投资金额 (USD)', 'enterAmount': '输入金额 (最低 $100)',
    'submitInvestment': '提交投资请求', 'processingText': '处理中...', 'minInvestment': '最低投资 $100',
    'paymentDetails': '付款详情', 'cardNumber': '卡号', 'copied': '已复制!', 'walletCopied': '钱包地址已复制!',
    'investmentHistory': '投资历史', 'noInvestments': '暂无投资', 'profit': '利润',
    'teslaStock': '特斯拉股票表现', 'signIn': '登录', 'signUp': '注册',
    'email': '电子邮件', 'password': '密码', 'fullName': '全名', 'welcomeBack': '欢迎回来',
    'heroTitle': '投资', 'heroTitleHighlight': '电动出行的未来',
    'getStarted': '开始', 'learnMore': '了解更多', 'language': '语言',
    'withdraw': '提款', 'withdrawalAmount': '提款金额', 'selectCountry': '选择您的国家',
    'bankCard': '银行卡', 'cryptoPayment': '加密货币', 'submitWithdrawal': '提交提款请求',
    'next': '下一步', 'back': '返回', 'contactSupport': '联系支持',
    'portfolioBalance': '投资组合余额', 'cryptoWarning': '请确保只存入 USDT',
    'network': '网络', 'walletAddress': 'USDT钱包地址', 'important': '重要',
    'referralCode': '推荐码', 'optional': '可选',
  },
  ar: {
    'home': 'الرئيسية', 'about': 'معلومات عنا', 'investments': 'الاستثمارات', 'security': 'الأمان', 'dashboard': 'لوحة التحكم',
    'invest': 'استثمر', 'signOut': 'تسجيل الخروج', 'admin': 'المشرف',
    'totalInvested': 'إجمالي المستثمر', 'totalProfit': 'إجمالي الربح', 'pending': 'قيد الانتظار', 'active': 'نشط',
    'paymentDetails': 'تفاصيل الدفع', 'cardNumber': 'رقم البطاقة', 'copied': 'تم النسخ!', 'walletCopied': 'تم نسخ عنوان المحفظة!',
    'signIn': 'تسجيل الدخول', 'signUp': 'إنشاء حساب',
    'heroTitle': 'استثمر في', 'heroTitleHighlight': 'مستقبل التنقل الكهربائي',
    'getStarted': 'ابدأ الآن', 'language': 'اللغة',
    'withdraw': 'سحب', 'selectCountry': 'اختر بلدك',
    'bankCard': 'بطاقة بنكية', 'cryptoPayment': 'عملة مشفرة',
    'next': 'التالي', 'back': 'رجوع',
    'portfolioBalance': 'رصيد المحفظة', 'cryptoWarning': 'تأكد من إيداع USDT فقط',
    'network': 'الشبكة', 'walletAddress': 'عنوان محفظة USDT', 'important': 'مهم',
    'referralCode': 'رمز الإحالة', 'optional': 'اختياري',
  },
  pt: {
    'home': 'Início', 'about': 'Sobre', 'investments': 'Investimentos', 'security': 'Segurança', 'dashboard': 'Painel',
    'invest': 'Investir', 'signOut': 'Sair', 'admin': 'Admin',
    'totalInvested': 'Total investido', 'totalProfit': 'Lucro total', 'pending': 'Pendente', 'active': 'Ativo',
    'paymentDetails': 'Detalhes de pagamento', 'cardNumber': 'Número do cartão', 'copied': 'Copiado!', 'walletCopied': 'Endereço da carteira copiado!',
    'signIn': 'Entrar', 'signUp': 'Registrar',
    'heroTitle': 'Invista no', 'heroTitleHighlight': 'Futuro da mobilidade elétrica',
    'getStarted': 'Começar', 'language': 'Idioma',
    'withdraw': 'Saque', 'selectCountry': 'Selecione seu país',
    'bankCard': 'Cartão bancário', 'cryptoPayment': 'Criptomoeda',
    'next': 'Próximo', 'back': 'Voltar',
    'portfolioBalance': 'Saldo do portfólio', 'cryptoWarning': 'Certifique-se de depositar apenas USDT',
    'network': 'Rede', 'walletAddress': 'Endereço da carteira USDT', 'important': 'Importante',
    'referralCode': 'Código de indicação', 'optional': 'opcional',
  },
  ja: {
    'home': 'ホーム', 'about': '会社概要', 'investments': '投資', 'security': 'セキュリティ', 'dashboard': 'ダッシュボード',
    'invest': '投資する', 'signOut': 'ログアウト', 'admin': '管理者',
    'totalInvested': '投資総額', 'totalProfit': '総利益', 'pending': '保留中', 'active': 'アクティブ',
    'paymentDetails': '支払い詳細', 'cardNumber': 'カード番号', 'copied': 'コピーしました!', 'walletCopied': 'ウォレットアドレスをコピーしました!',
    'signIn': 'ログイン', 'signUp': '登録',
    'heroTitle': '投資する', 'heroTitleHighlight': '電気モビリティの未来',
    'getStarted': '始める', 'language': '言語',
    'withdraw': '引き出し', 'selectCountry': '国を選択',
    'bankCard': '銀行カード', 'cryptoPayment': '暗号通貨',
    'next': '次へ', 'back': '戻る',
    'portfolioBalance': 'ポートフォリオ残高', 'cryptoWarning': 'USDTのみ入金してください',
    'network': 'ネットワーク', 'walletAddress': 'USDTウォレットアドレス', 'important': '重要',
    'referralCode': '紹介コード', 'optional': 'オプション',
  },
  ko: {
    'home': '홈', 'about': '소개', 'investments': '투자', 'security': '보안', 'dashboard': '대시보드',
    'invest': '투자', 'signOut': '로그아웃', 'admin': '관리자',
    'totalInvested': '총 투자', 'totalProfit': '총 수익', 'pending': '대기 중', 'active': '활성',
    'paymentDetails': '결제 정보', 'cardNumber': '카드 번호', 'copied': '복사됨!', 'walletCopied': '지갑 주소가 복사되었습니다!',
    'signIn': '로그인', 'signUp': '가입',
    'heroTitle': '투자하세요', 'heroTitleHighlight': '전기 이동성의 미래에',
    'getStarted': '시작하기', 'language': '언어',
    'withdraw': '인출', 'selectCountry': '국가 선택',
    'bankCard': '은행 카드', 'cryptoPayment': '암호화폐',
    'next': '다음', 'back': '이전',
    'portfolioBalance': '포트폴리오 잔액', 'cryptoWarning': 'USDT만 입금하세요',
    'network': '네트워크', 'walletAddress': 'USDT 지갑 주소', 'important': '중요',
    'referralCode': '추천 코드', 'optional': '선택 사항',
  },
  hi: {
    'home': 'होम', 'about': 'हमारे बारे में', 'investments': 'निवेश', 'security': 'सुरक्षा', 'dashboard': 'डैशबोर्ड',
    'invest': 'निवेश करें', 'signOut': 'लॉग आउट', 'admin': 'एडमिन',
    'totalInvested': 'कुल निवेश', 'totalProfit': 'कुल लाभ', 'pending': 'लंबित', 'active': 'सक्रिय',
    'paymentDetails': 'भुगतान विवरण', 'cardNumber': 'कार्ड नंबर', 'copied': 'कॉपी किया!', 'walletCopied': 'वॉलेट पता कॉपी किया गया!',
    'signIn': 'साइन इन', 'signUp': 'साइन अप',
    'heroTitle': 'निवेश करें', 'heroTitleHighlight': 'इलेक्ट्रिक मोबिलिटी के भविष्य में',
    'getStarted': 'शुरू करें', 'language': 'भाषा',
    'withdraw': 'निकासी', 'selectCountry': 'अपना देश चुनें',
    'bankCard': 'बैंक कार्ड', 'cryptoPayment': 'क्रिप्टोकरेंसी',
    'next': 'अगला', 'back': 'पीछे',
    'portfolioBalance': 'पोर्टफोलियो बैलेंस', 'cryptoWarning': 'केवल USDT जमा करें',
    'network': 'नेटवर्क', 'walletAddress': 'USDT वॉलेट पता', 'important': 'महत्वपूर्ण',
    'referralCode': 'रेफरल कोड', 'optional': 'वैकल्पिक',
  },
  it: {
    'home': 'Home', 'about': 'Chi siamo', 'investments': 'Investimenti', 'security': 'Sicurezza', 'dashboard': 'Dashboard',
    'invest': 'Investi', 'signOut': 'Esci', 'admin': 'Admin',
    'totalInvested': 'Totale investito', 'totalProfit': 'Profitto totale', 'pending': 'In attesa', 'active': 'Attivo',
    'paymentDetails': 'Dettagli pagamento', 'cardNumber': 'Numero carta', 'copied': 'Copiato!', 'walletCopied': 'Indirizzo portafoglio copiato!',
    'signIn': 'Accedi', 'signUp': 'Registrati',
    'heroTitle': 'Investi nel', 'heroTitleHighlight': 'Futuro della mobilità elettrica',
    'getStarted': 'Inizia', 'language': 'Lingua',
    'withdraw': 'Prelievo', 'selectCountry': 'Seleziona il tuo paese',
    'bankCard': 'Carta bancaria', 'cryptoPayment': 'Criptovaluta',
    'next': 'Avanti', 'back': 'Indietro',
    'portfolioBalance': 'Saldo portafoglio', 'cryptoWarning': 'Assicurati di depositare solo USDT',
    'network': 'Rete', 'walletAddress': 'Indirizzo portafoglio USDT', 'important': 'Importante',
    'referralCode': 'Codice referral', 'optional': 'opzionale',
  },
  tr: {
    'home': 'Ana Sayfa', 'about': 'Hakkımızda', 'investments': 'Yatırımlar', 'security': 'Güvenlik', 'dashboard': 'Panel',
    'invest': 'Yatırım Yap', 'signOut': 'Çıkış', 'admin': 'Yönetici',
    'totalInvested': 'Toplam Yatırım', 'totalProfit': 'Toplam Kâr', 'pending': 'Beklemede', 'active': 'Aktif',
    'paymentDetails': 'Ödeme Detayları', 'cardNumber': 'Kart Numarası', 'copied': 'Kopyalandı!', 'walletCopied': 'Cüzdan adresi kopyalandı!',
    'signIn': 'Giriş Yap', 'signUp': 'Kayıt Ol',
    'heroTitle': 'Yatırım Yapın', 'heroTitleHighlight': 'Elektrikli Mobilitenin Geleceğine',
    'getStarted': 'Başla', 'language': 'Dil',
    'withdraw': 'Çekme', 'selectCountry': 'Ülkenizi seçin',
    'bankCard': 'Banka Kartı', 'cryptoPayment': 'Kripto Para',
    'next': 'İleri', 'back': 'Geri',
    'portfolioBalance': 'Portföy Bakiyesi', 'cryptoWarning': 'Sadece USDT yatırın',
    'network': 'Ağ', 'walletAddress': 'USDT Cüzdan Adresi', 'important': 'Önemli',
    'referralCode': 'Referans Kodu', 'optional': 'isteğe bağlı',
  },
  vi: {
    'home': 'Trang chủ', 'about': 'Về chúng tôi', 'investments': 'Đầu tư', 'security': 'Bảo mật', 'dashboard': 'Bảng điều khiển',
    'invest': 'Đầu tư', 'signOut': 'Đăng xuất', 'admin': 'Quản trị',
    'totalInvested': 'Tổng đầu tư', 'totalProfit': 'Tổng lợi nhuận', 'pending': 'Đang chờ', 'active': 'Hoạt động',
    'paymentDetails': 'Chi tiết thanh toán', 'cardNumber': 'Số thẻ', 'copied': 'Đã sao chép!', 'walletCopied': 'Đã sao chép địa chỉ ví!',
    'signIn': 'Đăng nhập', 'signUp': 'Đăng ký',
    'heroTitle': 'Đầu tư vào', 'heroTitleHighlight': 'Tương lai của di chuyển điện',
    'getStarted': 'Bắt đầu', 'language': 'Ngôn ngữ',
    'withdraw': 'Rút tiền', 'selectCountry': 'Chọn quốc gia',
    'bankCard': 'Thẻ ngân hàng', 'cryptoPayment': 'Tiền điện tử',
    'next': 'Tiếp', 'back': 'Quay lại',
    'portfolioBalance': 'Số dư danh mục', 'cryptoWarning': 'Chỉ nạp USDT',
    'network': 'Mạng', 'walletAddress': 'Địa chỉ ví USDT', 'important': 'Quan trọng',
    'referralCode': 'Mã giới thiệu', 'optional': 'tùy chọn',
  },
  th: {
    'home': 'หน้าแรก', 'about': 'เกี่ยวกับเรา', 'investments': 'การลงทุน', 'security': 'ความปลอดภัย', 'dashboard': 'แดชบอร์ด',
    'invest': 'ลงทุน', 'signOut': 'ออกจากระบบ', 'admin': 'ผู้ดูแล',
    'totalInvested': 'ลงทุนทั้งหมด', 'totalProfit': 'กำไรทั้งหมด', 'pending': 'รอดำเนินการ', 'active': 'ใช้งานอยู่',
    'paymentDetails': 'รายละเอียดการชำระ', 'cardNumber': 'หมายเลขบัตร', 'copied': 'คัดลอกแล้ว!', 'walletCopied': 'คัดลอกที่อยู่กระเป๋าแล้ว!',
    'signIn': 'เข้าสู่ระบบ', 'signUp': 'ลงทะเบียน',
    'heroTitle': 'ลงทุนใน', 'heroTitleHighlight': 'อนาคตของการเดินทางด้วยไฟฟ้า',
    'getStarted': 'เริ่มต้น', 'language': 'ภาษา',
    'withdraw': 'ถอนเงิน', 'selectCountry': 'เลือกประเทศ',
    'bankCard': 'บัตรธนาคาร', 'cryptoPayment': 'คริปโตเคอเรนซี',
    'next': 'ถัดไป', 'back': 'กลับ',
    'portfolioBalance': 'ยอดพอร์ตโฟลิโอ', 'cryptoWarning': 'ฝากเฉพาะ USDT เท่านั้น',
    'network': 'เครือข่าย', 'walletAddress': 'ที่อยู่กระเป๋า USDT', 'important': 'สำคัญ',
    'referralCode': 'รหัสแนะนำ', 'optional': 'ไม่บังคับ',
  },
  hu: {
    'home': 'Főoldal', 'about': 'Rólunk', 'investments': 'Befektetések', 'security': 'Biztonság', 'dashboard': 'Irányítópult',
    'invest': 'Befektetés', 'signOut': 'Kijelentkezés', 'admin': 'Admin',
    'totalInvested': 'Összes befektetés', 'totalProfit': 'Összes profit', 'pending': 'Függőben', 'active': 'Aktív',
    'paymentDetails': 'Fizetési adatok', 'cardNumber': 'Kártyaszám', 'copied': 'Másolva!', 'walletCopied': 'Tárca címe másolva!',
    'signIn': 'Bejelentkezés', 'signUp': 'Regisztráció',
    'heroTitle': 'Fektessen be a', 'heroTitleHighlight': 'Elektromos mobilitás jövőjébe',
    'getStarted': 'Kezdés', 'language': 'Nyelv',
    'withdraw': 'Kifizetés', 'selectCountry': 'Válassza ki országát',
    'bankCard': 'Bankkártya', 'cryptoPayment': 'Kriptovaluta',
    'next': 'Következő', 'back': 'Vissza',
    'portfolioBalance': 'Portfólió egyenleg', 'cryptoWarning': 'Csak USDT befizetés',
    'network': 'Hálózat', 'walletAddress': 'USDT tárca címe', 'important': 'Fontos',
    'referralCode': 'Ajánlókód', 'optional': 'opcionális',
  },
  cs: {
    'home': 'Domů', 'about': 'O nás', 'investments': 'Investice', 'security': 'Bezpečnost', 'dashboard': 'Přehled',
    'invest': 'Investovat', 'signOut': 'Odhlásit se', 'admin': 'Admin',
    'totalInvested': 'Celkem investováno', 'totalProfit': 'Celkový zisk', 'pending': 'Čekající', 'active': 'Aktivní',
    'paymentDetails': 'Platební údaje', 'cardNumber': 'Číslo karty', 'copied': 'Zkopírováno!', 'walletCopied': 'Adresa peněženky zkopírována!',
    'signIn': 'Přihlásit se', 'signUp': 'Registrovat se',
    'heroTitle': 'Investujte do', 'heroTitleHighlight': 'Budoucnosti elektrické mobility',
    'getStarted': 'Začít', 'language': 'Jazyk',
    'withdraw': 'Výběr', 'selectCountry': 'Vyberte svou zemi',
    'bankCard': 'Bankovní karta', 'cryptoPayment': 'Kryptoměna',
    'next': 'Další', 'back': 'Zpět',
    'portfolioBalance': 'Zůstatek portfolia', 'cryptoWarning': 'Vkládejte pouze USDT',
    'network': 'Síť', 'walletAddress': 'Adresa USDT peněženky', 'important': 'Důležité',
    'referralCode': 'Referenční kód', 'optional': 'volitelné',
  },
  el: {
    'home': 'Αρχική', 'about': 'Σχετικά', 'investments': 'Επενδύσεις', 'security': 'Ασφάλεια', 'dashboard': 'Πίνακας ελέγχου',
    'invest': 'Επένδυση', 'signOut': 'Αποσύνδεση', 'admin': 'Διαχειριστής',
    'totalInvested': 'Συνολική επένδυση', 'totalProfit': 'Συνολικό κέρδος', 'pending': 'Εκκρεμεί', 'active': 'Ενεργό',
    'paymentDetails': 'Στοιχεία πληρωμής', 'cardNumber': 'Αριθμός κάρτας', 'copied': 'Αντιγράφηκε!', 'walletCopied': 'Η διεύθυνση πορτοφολιού αντιγράφηκε!',
    'signIn': 'Σύνδεση', 'signUp': 'Εγγραφή',
    'heroTitle': 'Επενδύστε στο', 'heroTitleHighlight': 'Μέλλον της ηλεκτρικής κινητικότητας',
    'getStarted': 'Ξεκινήστε', 'language': 'Γλώσσα',
    'withdraw': 'Ανάληψη', 'selectCountry': 'Επιλέξτε χώρα',
    'bankCard': 'Τραπεζική κάρτα', 'cryptoPayment': 'Κρυπτονόμισμα',
    'next': 'Επόμενο', 'back': 'Πίσω',
    'portfolioBalance': 'Υπόλοιπο χαρτοφυλακίου', 'cryptoWarning': 'Καταθέστε μόνο USDT',
    'network': 'Δίκτυο', 'walletAddress': 'Διεύθυνση πορτοφολιού USDT', 'important': 'Σημαντικό',
    'referralCode': 'Κωδικός παραπομπής', 'optional': 'προαιρετικό',
  },
  pl: {
    'home': 'Strona główna', 'about': 'O nas', 'investments': 'Inwestycje', 'security': 'Bezpieczeństwo', 'dashboard': 'Panel',
    'invest': 'Inwestuj', 'signOut': 'Wyloguj', 'admin': 'Admin',
    'totalInvested': 'Łączna inwestycja', 'totalProfit': 'Łączny zysk', 'pending': 'Oczekujące', 'active': 'Aktywne',
    'paymentDetails': 'Szczegóły płatności', 'cardNumber': 'Numer karty', 'copied': 'Skopiowano!', 'walletCopied': 'Adres portfela skopiowany!',
    'signIn': 'Zaloguj się', 'signUp': 'Zarejestruj się',
    'heroTitle': 'Zainwestuj w', 'heroTitleHighlight': 'Przyszłość elektrycznej mobilności',
    'getStarted': 'Rozpocznij', 'language': 'Język',
    'withdraw': 'Wypłata', 'selectCountry': 'Wybierz swój kraj',
    'bankCard': 'Karta bankowa', 'cryptoPayment': 'Kryptowaluta',
    'next': 'Dalej', 'back': 'Wstecz',
    'portfolioBalance': 'Saldo portfela', 'cryptoWarning': 'Wpłacaj tylko USDT',
    'network': 'Sieć', 'walletAddress': 'Adres portfela USDT', 'important': 'Ważne',
    'referralCode': 'Kod polecający', 'optional': 'opcjonalne',
  },
  ro: {
    'home': 'Acasă', 'about': 'Despre', 'investments': 'Investiții', 'security': 'Securitate', 'dashboard': 'Panou',
    'invest': 'Investește', 'signOut': 'Deconectare', 'admin': 'Admin',
    'totalInvested': 'Total investit', 'totalProfit': 'Profit total', 'pending': 'În așteptare', 'active': 'Activ',
    'paymentDetails': 'Detalii plată', 'cardNumber': 'Număr card', 'copied': 'Copiat!', 'walletCopied': 'Adresa portofelului copiată!',
    'signIn': 'Autentificare', 'signUp': 'Înregistrare',
    'heroTitle': 'Investește în', 'heroTitleHighlight': 'Viitorul mobilității electrice',
    'getStarted': 'Începe', 'language': 'Limbă',
    'withdraw': 'Retragere', 'selectCountry': 'Selectează țara',
    'bankCard': 'Card bancar', 'cryptoPayment': 'Criptomonedă',
    'next': 'Următorul', 'back': 'Înapoi',
    'portfolioBalance': 'Sold portofoliu', 'cryptoWarning': 'Depune doar USDT',
    'network': 'Rețea', 'walletAddress': 'Adresa portofelului USDT', 'important': 'Important',
    'referralCode': 'Cod de recomandare', 'optional': 'opțional',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    const fetchDefaultLanguage = async () => {
      const saved = localStorage.getItem('app-language');
      if (!saved) {
        try {
          const { data, error } = await supabase
            .from('admin_settings')
            .select('setting_value')
            .eq('setting_key', 'default_language')
            .maybeSingle();
          
          if (data && !error) {
            const defaultLang = (data.setting_value as { language: string })?.language;
            if (defaultLang) {
              setLanguage(defaultLang as Language);
              localStorage.setItem('app-language', defaultLang);
            }
          }
        } catch (err) {
          console.error('Error fetching default language:', err);
        }
      }
    };
    
    fetchDefaultLanguage();
  }, []);

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
